"""
This type stub file was generated by pyright.
"""

from typing import Any, Type
from bip_utils.bip.bip44_base import Bip44Base, Bip44PrivateKey, Bip44PublicKey
from bip_utils.bip.conf.bip44 import Bip44Coins
from bip_utils.brainwallet.brainwallet_algo import BrainwalletAlgos
from bip_utils.brainwallet.ibrainwallet_algo import IBrainwalletAlgo

"""Module for keys generation using a brainwallet (i.e. passphrase chosen by the user)."""
BrainwalletCoins = Bip44Coins
class Brainwallet:
    """
    Brainwallet class.
    It allows to generate a key pair from a passphrase chosen by the user
    for different coins and with different algorithms.
    """
    bip44_obj: Bip44Base
    @classmethod
    def Generate(cls, passhrase: str, coin_type: BrainwalletCoins, algo_type: BrainwalletAlgos, **algo_params: Any) -> Brainwallet:
        """
        Generate a brainwallet from the specified passphrase and coin with the specified algorithm.

        Args:
            passhrase (str)             : Passphrase
            coin_type (BrainwalletCoins): Coin type
            algo_type (BrainwalletAlgos): Algorithm type
            **algo_params               : Algorithm parameters, if any

        Returns:
            Brainwallet object: Algorithm class

        Raises:
            TypeError: If algorithm type is not of a BrainwalletAlgos enumerative
                       or coin type is not of a BrainwalletCoins enumerative
        """
        ...
    
    @classmethod
    def GenerateWithCustomAlgo(cls, passhrase: str, coin_type: BrainwalletCoins, algo_cls: Type[IBrainwalletAlgo], **algo_params: Any) -> Brainwallet:
        """
        Generate a brainwallet from the specified passphrase and coin with a custom algorithm.

        Args:
            passhrase (str)                  : Passphrase
            coin_type (BrainwalletCoins)     : Coin type
            algo_cls (IBrainwalletAlgo class): Algorithm class
            **algo_params                    : Algorithm parameters, if any

        Returns:
            Brainwallet object: Algorithm class

        Raises:
            TypeError: If algorithm type is not of a BrainwalletAlgos enumerative
                       or coin type is not of a BrainwalletCoins enumerative
        """
        ...
    
    def __init__(self, bip44_obj: Bip44Base) -> None:
        """
        Construct class.

        Args:
            bip44_obj (Bip44Base object): Bip44Base object
        """
        ...
    
    def PublicKey(self) -> Bip44PublicKey:
        """
        Return the public key.

        Returns:
            Bip44PublicKey object: Bip44PublicKey object
        """
        ...
    
    def PrivateKey(self) -> Bip44PrivateKey:
        """
        Return the private key.

        Returns:
            Bip44PrivateKey object: Bip44PrivateKey object
        """
        ...
    


