"""
This type stub file was generated by pyright.
"""

from enum import Enum, unique
from typing import Any
from bip_utils.brainwallet.ibrainwallet_algo import IBrainwalletAlgo

"""Module for implementing algorithms for brainwallet generation."""
@unique
class BrainwalletAlgos(Enum):
    """Enum for brainwallet algorithms."""
    SHA256 = ...
    DOUBLE_SHA256 = ...
    PBKDF2_HMAC_SHA512 = ...
    SCRYPT = ...


class BrainwalletAlgoConst:
    """Class container for brainwallet algorithm constants."""
    PBKDF2_HMAC_SHA512_KEY_LEN: int = ...
    PBKDF2_HMAC_SHA512_DEF_ITR_NUM: int = ...
    SCRYPT_KEY_LEN: int = ...
    SCRYPT_DEF_N: int = ...
    SCRYPT_DEF_P: int = ...
    SCRYPT_DEF_R: int = ...


class BrainwalletAlgoSha256(IBrainwalletAlgo):
    """Compute the private key from passphrase using SHA256 algorithm."""
    @staticmethod
    def ComputePrivateKey(passphrase: str, **kwargs: Any) -> bytes:
        """
        Compute the private key from the specified passphrase.

        Args:
            passphrase (str): Passphrase
            **kwargs        : Not used

        Returns:
            bytes: Private key bytes
        """
        ...
    


class BrainwalletAlgoDoubleSha256(IBrainwalletAlgo):
    """Compute the private key from passphrase using double SHA256 algorithm."""
    @staticmethod
    def ComputePrivateKey(passphrase: str, **kwargs: Any) -> bytes:
        """
        Compute the private key from the specified passphrase.

        Args:
            passphrase (str): Passphrase
            **kwargs        : Not used

        Returns:
            bytes: Private key bytes
        """
        ...
    


class BrainwalletAlgoPbkdf2HmacSha512(IBrainwalletAlgo):
    """Compute the private key from passphrase using PBKDF2 HMAC-SHA512 algorithm."""
    @staticmethod
    def ComputePrivateKey(passphrase: str, **kwargs: Any) -> bytes:
        """
        Compute the private key from the specified passphrase.

        Args:
            passphrase (str): Passphrase

        Other Parameters:
            salt (str)   : Salt for PBKDF2 algorithm (default: empty)
            itr_num (int): Number of iteration for PBKDF2 algorithm (default: 2097152)

        Returns:
            bytes: Private key bytes
        """
        ...
    


class BrainwalletAlgoScrypt(IBrainwalletAlgo):
    """Compute the private key from passphrase using Scrypt algorithm."""
    @staticmethod
    def ComputePrivateKey(passphrase: str, **kwargs: Any) -> bytes:
        """
        Compute the private key from the specified passphrase.

        Args:
            passphrase (str): Passphrase

        Other Parameters:
            salt (str): Salt for Scrypt algorithm (default: empty)
            n (int)   : CPU/Memory cost parameter for Scrypt algorithm (default: 131072)
            r (int)   : Block size parameter for Scrypt algorithm (default: 8)
            p (int)   : Parallelization parameter for Scrypt algorithm (default: 8)

        Returns:
            bytes: Private key bytes
        """
        ...
    


