"""
This type stub file was generated by pyright.
"""

from typing import Dict, Type
from bip_utils.brainwallet.brainwallet_algo import BrainwalletAlgos
from bip_utils.brainwallet.ibrainwallet_algo import IBrainwalletAlgo

"""Module for getting brainwallet algorithms."""
class BrainwalletAlgoGetterConst:
    """Class container for brainwallet algorithm getter constants."""
    ENUM_TO_ALGO: Dict[BrainwalletAlgos, Type[IBrainwalletAlgo]] = ...


class BrainwalletAlgoGetter:
    """
    Brainwallet algorithm getter class.
    It allows to get the a specific brainwallet algorithm.
    """
    @staticmethod
    def GetAlgo(algo_type: BrainwalletAlgos) -> Type[IBrainwalletAlgo]:
        """
        Get algorithm class.

        Args:
            algo_type (BrainwalletAlgos): Algorithm type

        Returns:
            IBrainwalletAlgo class: Algorithm class

        Raises:
            TypeError: If algorithm type is not of a BrainwalletAlgos enumerative
        """
        ...
    


