"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import Any

"""Module for implementing algorithms for brainwallet generation."""
class IBrainwalletAlgo(ABC):
    """
    Interface for an algorithm that computes a private key for a brainwallet.
    It can be inherited to implement custom algorithms.
    """
    @staticmethod
    @abstractmethod
    def ComputePrivateKey(passphrase: str, **kwargs: Any) -> bytes:
        """
        Compute the private key from the specified passphrase.

        Args:
            passphrase (str): Passphrase
            **kwargs        : Arbitrary arguments depending on the algorithm

        Returns:
            bytes: Private key bytes
        """
        ...
    


