"""
This type stub file was generated by pyright.
"""

from typing import Tuple, Union
from bip_utils.addr import P2PKHPubKeyModes
from bip_utils.ecc import IPrivateKey

"""Module for WIF encoding/decoding."""
WifPubKeyModes = P2PKHPubKeyModes
class WifConst:
    """Class container for WIF constants."""
    COMPR_PUB_KEY_SUFFIX: bytes = ...


class WifEncoder:
    """
    WIF encoder class.
    It provides methods for encoding to WIF format.
    """
    @staticmethod
    def Encode(priv_key: Union[bytes, IPrivateKey], net_ver: bytes = ..., pub_key_mode: WifPubKeyModes = ...) -> str:
        """
        Encode key bytes into a WIF string.

        Args:
            priv_key (bytes or IPrivateKey)        : Private key bytes or object
            net_ver (bytes, optional)              : Net version (Bitcoin main net by default)
            pub_key_mode (WifPubKeyModes, optional): Specify if the private key corresponds to a compressed public key

        Returns:
            str: WIF encoded string

        Raises:
            TypeError: If pub_key_mode is not a WifPubKeyModes enum or
                       the private key is not a valid Secp256k1PrivateKey
            ValueError: If the key is not valid
        """
        ...
    


class WifDecoder:
    """
    WIF encoder class.
    It provides methods for encoding to WIF format.
    """
    @staticmethod
    def Decode(wif_str: str, net_ver: bytes = ...) -> Tuple[bytes, WifPubKeyModes]:
        """
        Decode key bytes from a WIF string.

        Args:
            wif_str (str)            : WIF string
            net_ver (bytes, optional): Net version (Bitcoin main net by default)

        Returns:
            tuple[bytes, WifPubKeyModes]: Key bytes (index 0), public key mode (index 1)

        Raises:
            Base58ChecksumError: If the base58 checksum is not valid
            ValueError: If the resulting key is not valid
        """
        ...
    


