"""
This type stub file was generated by pyright.
"""

from typing import Optional, Union
from bip_utils.monero.mnemonic.monero_mnemonic import MoneroLanguages
from bip_utils.utils.mnemonic import Mnemonic, MnemonicDecoderBase

"""Module for Monero mnemonic decoding."""
class MoneroMnemonicDecoder(MnemonicDecoderBase):
    """
    Monero mnemonic decoder class.
    It decodes a mnemonic phrase to bytes.
    """
    def __init__(self, lang: Optional[MoneroLanguages] = ...) -> None:
        """
        Construct class.

        Args:
            lang (MoneroLanguages, optional): Language, None for automatic detection

        Raises:
            TypeError: If the language is not a MoneroLanguages enum
            ValueError: If loaded words list is not valid
        """
        ...
    
    def Decode(self, mnemonic: Union[str, Mnemonic]) -> bytes:
        """
        Decode a mnemonic phrase to bytes (no checksum).

        Args:
            mnemonic (str or Mnemonic object): Mnemonic

        Returns:
            bytes: Decoded bytes

        Raises:
            MnemonicChecksumError: If checksum is not valid
            ValueError: If mnemonic is not valid
        """
        ...
    


