"""
This type stub file was generated by pyright.
"""

from enum import IntEnum, unique
from typing import List, Union
from bip_utils.utils.mnemonic import EntropyGenerator

"""Module for Monero entropy generation."""
@unique
class MoneroEntropyBitLen(IntEnum):
    """Enumerative for Monero entropy bit lengths."""
    BIT_LEN_128 = ...
    BIT_LEN_256 = ...


class MoneroEntropyGeneratorConst:
    """Class container for Monero entropy generator constants."""
    ENTROPY_BIT_LEN: List[MoneroEntropyBitLen] = ...


class MoneroEntropyGenerator(EntropyGenerator):
    """
    Monero entropy generator class.
    It generates random entropy bytes with the specified length.
    """
    def __init__(self, bit_len: Union[int, MoneroEntropyBitLen]) -> None:
        """
        Construct class.

        Args:
            bit_len (int or MoneroEntropyBitLen): Entropy length in bits

        Raises:
            ValueError: If the bit length is not valid
        """
        ...
    
    @staticmethod
    def IsValidEntropyBitLen(bit_len: Union[int, MoneroEntropyBitLen]) -> bool:
        """
        Get if the specified entropy bit length is valid.

        Args:
            bit_len (int or MoneroEntropyBitLen): Entropy length in bits

        Returns:
            bool: True if valid, false otherwise
        """
        ...
    
    @staticmethod
    def IsValidEntropyByteLen(byte_len: int) -> bool:
        """
        Get if the specified entropy byte length is valid.

        Args:
            byte_len (int): Entropy length in bytes

        Returns:
            bool: True if valid, false otherwise
        """
        ...
    


