"""
This type stub file was generated by pyright.
"""

from enum import unique
from bip_utils.bip.conf.common.bip_coins import BipCoins

"""Module for CIP-1852 coins enum."""
@unique
class Cip1852Coins(BipCoins):
    """Enumerative for supported CIP-1852 coins."""
    CARDANO_ICARUS = ...
    CARDANO_LEDGER = ...
    CARDANO_ICARUS_TESTNET = ...
    CARDANO_LEDGER_TESTNET = ...


