"""
This type stub file was generated by pyright.
"""

from typing import Optional, Union
from bip_utils.electrum.mnemonic_v1.electrum_v1_mnemonic import ElectrumV1Languages
from bip_utils.utils.mnemonic import Mnemonic

"""Module for Electrum v1 mnemonic seed generation."""
class ElectrumV1SeedGeneratorConst:
    """Class container for Electrum v1 seed generator constants."""
    HASH_ITR_NUM: int = ...


class ElectrumV1SeedGenerator:
    """
    Electrum seed generator class (v1).
    It generates the seed from a mnemonic.
    """
    m_seed: bytes
    def __init__(self, mnemonic: Union[str, Mnemonic], lang: Optional[ElectrumV1Languages] = ...) -> None:
        """
        Construct class.
        Language is set to English by default because Electrum v1 mnemonic only support one language,
        so it's useless (and slower) to automatically detect the language.

        Args:
            mnemonic (str or Mnemonic object)   : Mnemonic
            lang (ElectrumV1Languages, optional): Language, None for automatic detection

        Raises:
            ValueError: If the mnemonic is not valid
        """
        ...
    
    def Generate(self) -> bytes:
        """
        Generate seed.
        There is no really need of this method, since the seed is always the same, but it's
        kept in this way to have the same usage of Bip39/Substrate seed generator
        (i.e. ElectrumV1SeedGenerator(mnemonic).Generate() ).

        Returns:
            bytes: Generated seed
        """
        ...
    


