"""
This type stub file was generated by pyright.
"""

from typing import Dict, Union
from bip_utils.electrum.mnemonic_v1.electrum_v1_entropy_generator import ElectrumV1EntropyBitLen
from bip_utils.electrum.mnemonic_v1.electrum_v1_mnemonic import ElectrumV1Languages, ElectrumV1WordsNum
from bip_utils.electrum.mnemonic_v1.electrum_v1_mnemonic_encoder import ElectrumV1MnemonicEncoder
from bip_utils.utils.mnemonic import Mnemonic

"""Module for Electrum v1 mnemonic generation."""
class ElectrumV1MnemonicGeneratorConst:
    """Class container for Electrum v1 mnemonic generator constants."""
    WORDS_NUM_TO_ENTROPY_LEN: Dict[ElectrumV1WordsNum, ElectrumV1EntropyBitLen] = ...


class ElectrumV1MnemonicGenerator:
    """
    Electrum v1 mnemonic generator class.
    It generates 12-words mnemonic in according to v1 Electrum mnemonic.
    """
    m_mnemonic_encoder: ElectrumV1MnemonicEncoder
    def __init__(self, lang: ElectrumV1Languages = ...) -> None:
        """
        Construct class.

        Args:
            lang (ElectrumV1Languages, optional): Language (default: English)

        Raises:
            TypeError: If the language is not a ElectrumV1Languages enum
            ValueError: If language words list is not valid
        """
        ...
    
    def FromWordsNumber(self, words_num: Union[int, ElectrumV1WordsNum]) -> Mnemonic:
        """
        Generate mnemonic with the specified words number from random entropy.
        There is no really need of this method, since the words number can only be 12, but it's
        kept to have the same usage of Bip39/Monero mnemonic generator.

        Args:
            words_num (int or ElectrumV1WordsNum): Number of words (12)

        Returns:
            Mnemonic object: Generated mnemonic

        Raises:
            ValueError: If words number is not valid
        """
        ...
    
    def FromEntropy(self, entropy_bytes: bytes) -> Mnemonic:
        """
        Generate mnemonic from the specified entropy bytes.

        Args:
            entropy_bytes (bytes): Entropy bytes

        Returns:
            Mnemonic object: Generated mnemonic

        Raises:
            ValueError: If entropy byte length is not valid
        """
        ...
    


