"""
This type stub file was generated by pyright.
"""

from enum import IntEnum, unique
from typing import Dict, List
from bip_utils.bip.bip39 import Bip39Mnemonic
from bip_utils.utils.mnemonic import MnemonicLanguages

"""Module for Electrum v1 mnemonic."""
@unique
class ElectrumV1WordsNum(IntEnum):
    """Enumerative for Electrum words number (v1)."""
    WORDS_NUM_12 = ...


@unique
class ElectrumV1Languages(MnemonicLanguages):
    """Enumerative for Electrum languages (v1)."""
    ENGLISH = ...


class ElectrumV1MnemonicConst:
    """Class container for Electrum v1 mnemonic constants."""
    MNEMONIC_WORD_NUM: List[ElectrumV1WordsNum] = ...
    LANGUAGE_FILES: Dict[MnemonicLanguages, str] = ...
    WORDS_LIST_NUM: int = ...


class ElectrumV1Mnemonic(Bip39Mnemonic):
    """Electrum v1 mnemonic class."""
    ...


