"""
This type stub file was generated by pyright.
"""

from bip_utils.electrum.mnemonic_v1.electrum_v1_mnemonic import ElectrumV1Languages
from bip_utils.utils.mnemonic import Mnemonic, MnemonicEncoderBase

"""
Module for Electrum v1 mnemonic encoding.
Reference: https://github.com/spesmilo/electrum
"""
class ElectrumV1MnemonicEncoder(MnemonicEncoderBase):
    """
    Electrum v1 mnemonic encoder class.
    It encodes bytes to the mnemonic phrase.
    """
    def __init__(self, lang: ElectrumV1Languages = ...) -> None:
        """
        Construct class.

        Args:
            lang (ElectrumV1Languages, optional): Language (default: English)

        Raises:
            TypeError: If the language is not a ElectrumV1Languages enum
            ValueError: If loaded words list is not valid
        """
        ...
    
    def Encode(self, entropy_bytes: bytes) -> Mnemonic:
        """
        Encode bytes to mnemonic phrase.

        Args:
            entropy_bytes (bytes): Entropy bytes (accepted lengths in bits: 128)

        Returns:
            Mnemonic object: Encoded mnemonic

        Raises:
            ValueError: If bytes length is not valid
        """
        ...
    


