"""
This type stub file was generated by pyright.
"""

import logging

"""
Functions to aid library logging. The default logging
:data:`~stem.util.log.Runlevel` is usually NOTICE and above.

**Stem users are more than welcome to listen for stem events, but these
functions are not being vended to our users. They may change in the future, use
them at your own risk.**

**Module Overview:**

::

  get_logger - provides the stem's Logger instance
  logging_level - converts a runlevel to its logging number
  escape - escapes special characters in a message in preparation for logging

  log - logs a message at the given runlevel
  log_once - logs a message, deduplicating if it has already been logged
  trace - logs a message at the TRACE runlevel
  debug - logs a message at the DEBUG runlevel
  info - logs a message at the INFO runlevel
  notice - logs a message at the NOTICE runlevel
  warn - logs a message at the WARN runlevel
  error - logs a message at the ERROR runlevel

  LogBuffer - Buffers logged events so they can be iterated over.
    |- is_empty - checks if there's events in our buffer
    +- __iter__ - iterates over and removes the buffered events

  log_to_stdout - reports further logged events to stdout

.. data:: Runlevel (enum)

  Enumeration for logging runlevels.

  ========== ===========
  Runlevel   Description
  ========== ===========
  **ERROR**  critical issue occurred, the user needs to be notified
  **WARN**   non-critical issue occurred that the user should be aware of
  **NOTICE** information that is helpful to the user
  **INFO**   high level library activity
  **DEBUG**  low level library activity
  **TRACE**  request/reply logging
  ========== ===========
"""
Runlevel = ...
LOG_VALUES = ...
LOGGER = ...
FORMATTER = ...
DEDUPLICATION_MESSAGE_IDS = ...
class _NullHandler(logging.Handler):
  def __init__(self) -> None:
    ...
  
  def emit(self, record): # -> None:
    ...
  


if not LOGGER.handlers:
  ...
def get_logger(): # -> Logger:
  """
  Provides the stem logger.

  :returns: **logging.Logger** for stem
  """
  ...

def logging_level(runlevel): # -> int:
  """
  Translates a runlevel into the value expected by the logging module.

  :param stem.util.log.Runlevel runlevel: runlevel to be returned, no logging if **None**
  """
  ...

def is_tracing(): # -> bool:
  """
  Checks if we're logging at the trace runlevel.

  .. versionadded:: 1.6.0

  :returns: **True** if we're logging at the trace runlevel and **False** otherwise
  """
  ...

def escape(message):
  """
  Escapes specific sequences for logging (newlines, tabs, carriage returns). If
  the input is **bytes** then this converts it to **unicode** under python 3.x.

  :param str message: string to be escaped

  :returns: str that is escaped
  """
  ...

def log(runlevel, message): # -> None:
  """
  Logs a message at the given runlevel.

  :param stem.util.log.Runlevel runlevel: runlevel to log the message at, logging is skipped if **None**
  :param str message: message to be logged
  """
  ...

def log_once(message_id, runlevel, message): # -> Literal[False] | None:
  """
  Logs a message at the given runlevel. If a message with this ID has already
  been logged then this is a no-op.

  :param str message_id: unique message identifier to deduplicate on
  :param stem.util.log.Runlevel runlevel: runlevel to log the message at, logging is skipped if **None**
  :param str message: message to be logged

  :returns: **True** if we log the message, **False** otherwise
  """
  ...

def trace(message): # -> None:
  ...

def debug(message): # -> None:
  ...

def info(message): # -> None:
  ...

def notice(message): # -> None:
  ...

def warn(message): # -> None:
  ...

def error(message): # -> None:
  ...

class LogBuffer(logging.Handler):
  """
  Basic log handler that listens for stem events and stores them so they can be
  read later. Log entries are cleared as they are read.

  .. versionchanged:: 1.4.0
     Added the yield_records argument.

  .. deprecated:: 1.8.0
     This will be dropped in Stem 2.x. Use python's logging.BufferingHandler instead.
  """
  def __init__(self, runlevel, yield_records=...) -> None:
    ...
  
  def is_empty(self): # -> bool:
    ...
  
  def __iter__(self): # -> Generator[Any | str, Any, None]:
    ...
  
  def emit(self, record): # -> None:
    ...
  


class _StdoutLogger(logging.Handler):
  def __init__(self, runlevel) -> None:
    ...
  
  def emit(self, record): # -> None:
    ...
  


def log_to_stdout(runlevel): # -> None:
  """
  Logs further events to stdout.

  :param stem.util.log.Runlevel runlevel: minimum runlevel a message needs to be to be logged
  """
  ...

