"""
This type stub file was generated by pyright.
"""

from enum import Enum, unique
from typing import Callable, Tuple, Type, TypeVar, Union
from bip_utils.ecc import IPublicKey

"""Module with utility functions for address decoding."""
BytesOrStr = TypeVar("BytesOrStr", bytes, str)
@unique
class ChecksumPositions(Enum):
    """Enumerative for checksum positions."""
    BEGINNING = ...
    END = ...


class AddrDecUtils:
    """Class container for address decoding utility functions."""
    @staticmethod
    def ValidateAndRemovePrefix(addr: BytesOrStr, prefix: BytesOrStr) -> BytesOrStr:
        """
        Validate and remove prefix from an address.

        Args:
            addr (bytes or str)  : Address string or bytes
            prefix (bytes or str): Address prefix

        Returns:
            bytes or str: Address string or bytes with prefix removed

        Raises:
            ValueError: If the prefix is not valid
        """
        ...
    
    @staticmethod
    def ValidateLength(addr: Union[bytes, str], len_exp: int) -> None:
        """
        Validate address length.

        Args:
            addr (bytes or str): Address string or bytes
            len_exp (int)      : Expected address length

        Raises:
            ValueError: If the length is not valid
        """
        ...
    
    @staticmethod
    def ValidatePubKey(pub_key_bytes: bytes, pub_key_cls: Type[IPublicKey]) -> None:
        """
        Validate address length.

        Args:
            pub_key_bytes (bytes)   : Public key bytes
            pub_key_cls (IPublicKey): Public key class type

        Raises:
            ValueError: If the public key is not valid
        """
        ...
    
    @staticmethod
    def ValidateChecksum(payload: BytesOrStr, checksum_exp: BytesOrStr, checksum_fct: Callable[[BytesOrStr], BytesOrStr]) -> None:
        """
        Validate address checksum.

        Args:
            payload (bytes or str)     : Payload string or bytes
            checksum_exp (bytes or str): Expected checksum string or bytes
            checksum_fct (function)    : Function for computing checksum

        Raises:
            ValueError: If the computed checksum is not equal to the specified one
        """
        ...
    
    @staticmethod
    def SplitPartsByChecksum(addr: BytesOrStr, checksum_len: int, checksum_pos: ChecksumPositions = ...) -> Tuple[BytesOrStr, BytesOrStr]:
        """
        Split address in two parts, payload and checksum.

        Args:
            addr (bytes or str)       : Address string or bytes
            checksum_len (int)        : Checksum length
            checksum_pos (bool): True if checksum is at the end of the address, false if it is at the beginning

        Returns:
            tuple[bytes or str, bytes or str]: Payload (index 0) and checksum (index 1)
        """
        ...
    


