"""
This type stub file was generated by pyright.
"""

from typing import Any, Union
from bip_utils.addr.iaddr_decoder import IAddrDecoder
from bip_utils.addr.iaddr_encoder import IAddrEncoder
from bip_utils.ecc import IPublicKey

"""Module for Algorand address encoding/decoding."""
class AlgoAddrConst:
    """Class container for Algorand address constants."""
    CHECKSUM_BYTE_LEN: int = ...


class _AlgoAddrUtils:
    """Algorand address utility class."""
    @staticmethod
    def ComputeChecksum(pub_key_bytes: bytes) -> bytes:
        """
        Compute checksum in Algorand format.

        Args:
            pub_key_bytes (bytes): Public key bytes

        Returns:
            bytes: Computed checksum
        """
        ...
    


class AlgoAddrDecoder(IAddrDecoder):
    """
    Algorand address decoder class.
    It allows the Algorand address decoding.
    """
    @staticmethod
    def DecodeAddr(addr: str, **kwargs: Any) -> bytes:
        """
        Decode an Algorand address to bytes.

        Args:
            addr (str): Address string
            **kwargs  : Not used

        Returns:
            bytes: Public key bytes

        Raises:
            ValueError: If the address encoding is not valid
        """
        ...
    


class AlgoAddrEncoder(IAddrEncoder):
    """
    Algorand address encoder class.
    It allows the Algorand address encoding.
    """
    @staticmethod
    def EncodeKey(pub_key: Union[bytes, IPublicKey], **kwargs: Any) -> str:
        """
        Encode a public key to Algorand address.

        Args:
            pub_key (bytes or IPublicKey): Public key bytes or object
            **kwargs                     : Not used

        Returns:
            str: Address string

        Raises:
            ValueError: If the public key is not valid
            TypeError: If the public key is not ed25519
        """
        ...
    


AlgoAddr = AlgoAddrEncoder
