"""
This type stub file was generated by pyright.
"""

from enum import IntEnum, unique
from typing import Any, Union
from bip_utils.addr.iaddr_decoder import IAddrDecoder
from bip_utils.addr.iaddr_encoder import IAddrEncoder
from bip_utils.ecc import IPublicKey

"""Module for Ergo address encoding/decoding."""
@unique
class ErgoAddressTypes(IntEnum):
    """Enumerative for Ergo address types."""
    P2PKH = ...
    P2SH = ...


@unique
class ErgoNetworkTypes(IntEnum):
    """Enumerative for Ergo network types."""
    MAINNET = ...
    TESTNET = ...


class ErgoAddrConst:
    """Class container for Ergo address constants."""
    CHECKSUM_BYTE_LEN: int = ...


class _ErgoAddrUtils:
    """Ergo address utility class."""
    @staticmethod
    def ComputeChecksum(pub_key_bytes: bytes) -> bytes:
        """
        Compute checksum in Ergo format.

        Args:
            pub_key_bytes (bytes): Public key bytes

        Returns:
            bytes: Computed checksum
        """
        ...
    
    @staticmethod
    def EncodePrefix(addr_type: ErgoAddressTypes, net_type: ErgoNetworkTypes) -> bytes:
        """
        Encode prefix.

        Args:
            addr_type (ErgoAddressTypes): Address type
            net_type (ErgoNetworkTypes) : Network type

        Returns:
            bytes: Prefix byte
        """
        ...
    


class ErgoP2PKHAddrDecoder(IAddrDecoder):
    """
    Ergo P2PKH address decoder class.
    It allows the Ergo P2PKH address decoding.
    """
    @staticmethod
    def DecodeAddr(addr: str, **kwargs: Any) -> bytes:
        """
        Decode an Ergo P2PKH address to bytes.

        Args:
            addr (str): Address string

        Other Parameters:
            net_type (ErgoNetworkTypes): Expected network type (default: main net)

        Returns:
            bytes: Public key bytes

        Raises:
            ValueError: If the address encoding is not valid
            TypeError: If the network tag is not a ErgoNetworkTypes enum
        """
        ...
    


class ErgoP2PKHAddrEncoder(IAddrEncoder):
    """
    Ergo P2PKH address encoder class.
    It allows the Ergo P2PKH address encoding.
    """
    @staticmethod
    def EncodeKey(pub_key: Union[bytes, IPublicKey], **kwargs: Any) -> str:
        """
        Encode a public key to Ergo P2PKH address.

        Args:
            pub_key (bytes or IPublicKey): Public key bytes or object

        Other Parameters:
            net_type (ErgoNetworkTypes): Network type (default: main net)

        Returns:
            str: Address string

        Raised:
            ValueError: If the public key is not valid
            TypeError: If the public key is not secp256k1 or the network tag is not a ErgoNetworkTypes enum
        """
        ...
    


ErgoP2PKHAddr = ErgoP2PKHAddrEncoder
