"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import Any, Union
from bip_utils.ecc import IPublicKey

"""Module with interface for address encoding classes."""
class IAddrEncoder(ABC):
    """Address encoder interface."""
    @staticmethod
    @abstractmethod
    def EncodeKey(pub_key: Union[bytes, IPublicKey], **kwargs: Any) -> str:
        """
        Encode public key to address.

        Args:
            pub_key (bytes or IPublicKey): Public key bytes or object
            **kwargs                     : Arbitrary arguments depending on the address type

        Returns:
            str: Address string

        Raised:
            ValueError: If the public key is not valid
            TypeError: If the public key is not of the correct type (it depends on the address type)
        """
        ...
    


