"""
This type stub file was generated by pyright.
"""

from enum import Enum, unique
from typing import Any, Union
from bip_utils.addr.iaddr_decoder import IAddrDecoder
from bip_utils.addr.iaddr_encoder import IAddrEncoder
from bip_utils.ecc import IPublicKey

"""Module for Mavryk address encoding/decoding."""
@unique
class MvrkAddrPrefixes(Enum):
    """Enumerative for Mavryk address prefixes."""
    MV1 = ...
    MV2 = ...
    MV3 = ...


class MvrkAddrDecoder(IAddrDecoder):
    """
    Mavryk address decoder class.
    It allows the Mavryk address decoding.
    """
    @staticmethod
    def DecodeAddr(addr: str, **kwargs: Any) -> bytes:
        """
        Decode a Mavryk address to bytes.

        Args:
            addr (str): Address string

        Other Parameters:
            prefix (MvrkAddrPrefixes): Expected address prefix

        Returns:
            bytes: Public key hash bytes

        Raises:
            ValueError: If the address encoding is not valid
            TypeError: If the prefix is not a MvrkAddrPrefixes enum
        """
        ...
    


class MvrkAddrEncoder(IAddrEncoder):
    """
    Mavryk address encoder class.
    It allows the Mavryk address encoding.
    """
    @staticmethod
    def EncodeKey(pub_key: Union[bytes, IPublicKey], **kwargs: Any) -> str:
        """
        Encode a public key to Mavryk address.

        Args:
            pub_key (bytes or IPublicKey): Public key bytes or object

        Other Parameters:
            prefix (MvrkAddrPrefixes): Address prefix

        Returns:
            str: Address string

        Raises:
            ValueError: If the public key is not valid
            TypeError: If the public key is not ed25519 or the prefix is not a MvrkAddrPrefixes enum
        """
        ...
    


MvrkAddr = MvrkAddrEncoder
