"""
This type stub file was generated by pyright.
"""

from typing import Any, Union
from bip_utils.addr.iaddr_decoder import IAddrDecoder
from bip_utils.addr.iaddr_encoder import IAddrEncoder
from bip_utils.ecc import IPublicKey

"""Module for Nimiq address encoding/decoding."""
class NimAddrConst:
    """Class container for Nimiq address constants."""
    ADDR_GROUP_LEN: int = ...
    CHECKSUM_ENC_LEN: int = ...
    BASE32_ALPHABET: str = ...
    HASH_BYTE_LEN: int = ...
    HASH_ENC_LEN: int = ...


class _NimAddrUtils:
    """Class container for Nimiq address utility functions."""
    @classmethod
    def ComputeChecksum(cls, addr_base32: str) -> str:
        """
        Compute checksum in Nimiq format.

        Args:
            addr_base32 (str): Address base32 encoded

        Returns:
            str: Computed checksum encoded to string
        """
        ...
    


class NimAddrDecoder(IAddrDecoder):
    """
    Nimiq address decoder class.
    It allows the Nimiq address decoding.
    """
    @staticmethod
    def DecodeAddr(addr: str, **kwargs: Any) -> bytes:
        """
        Decode an Nimiq address to bytes.

        Args:
            addr (str): Address string
            **kwargs  : Not used

        Returns:
            bytes: Public key hash bytes

        Raises:
            ValueError: If the address encoding is not valid
        """
        ...
    


class NimAddrEncoder(IAddrEncoder):
    """
    Nimiq address encoder class.
    It allows the Nimiq address encoding.
    """
    @staticmethod
    def EncodeKey(pub_key: Union[bytes, IPublicKey], **kwargs: Any) -> str:
        """
        Encode a public key to Nimiq address.

        Args:
            pub_key (bytes or IPublicKey): Public key bytes or object
            **kwargs                     : Not used

        Returns:
            str: Address string

        Raises:
            ValueError: If the public key is not valid
            TypeError: If the public key is not ed25519
        """
        ...
    


NimAddr = NimAddrEncoder
