"""
This type stub file was generated by pyright.
"""

from typing import Any, Union
from bip_utils.addr.iaddr_decoder import IAddrDecoder
from bip_utils.addr.iaddr_encoder import IAddrEncoder
from bip_utils.ecc import IPublicKey

"""Module for Solana address encoding/decoding."""
class SuiAddrConst:
    """Class container for Sui address constants."""
    KEY_TYPE: bytes = ...


class SuiAddrDecoder(IAddrDecoder):
    """
    Sui address decoder class.
    It allows the Sui address decoding.
    """
    @staticmethod
    def DecodeAddr(addr: str, **kwargs: Any) -> bytes:
        """
        Decode a Sui address to bytes.

        Args:
            addr (str): Address string
            **kwargs  : Not used

        Returns:
            bytes: Public key hash bytes

        Raises:
            ValueError: If the address encoding is not valid
        """
        ...
    


class SuiAddrEncoder(IAddrEncoder):
    """
    Sui address encoder class.
    It allows the Sui address encoding.
    """
    @staticmethod
    def EncodeKey(pub_key: Union[bytes, IPublicKey], **kwargs: Any) -> str:
        """
        Encode a public key to Sui address.

        Args:
            pub_key (bytes or IPublicKey): Public key bytes or object
            **kwargs                     : Not used

        Returns:
            str: Address string

        Raises:
            ValueError: If the public key is not valid
            TypeError: If the public key is not ed25519
        """
        ...
    


SuiAddr = SuiAddrEncoder
