"""
This type stub file was generated by pyright.
"""

from abc import ABC
from typing import Tuple, Union
from bip_utils.bip.bip32.base import IBip32KeyDerivator
from bip_utils.bip.bip32.bip32_key_data import Bip32KeyIndex
from bip_utils.bip.bip32.bip32_keys import Bip32PrivateKey, Bip32PublicKey
from bip_utils.ecc import IPoint

"""
Module for BIP32 Khovratovich/Law keys derivation (base).
Reference: https://github.com/LedgerHQ/orakolo/blob/master/papers/Ed25519_BIP%20Final.pdf
"""
class Bip32KholawEd25519KeyDerivatorBase(IBip32KeyDerivator, ABC):
    """
    BIP32 Khovratovich/Law ed25519 key derivator base class.
    It allows keys derivation for ed25519 curves in according to BIP32 Khovratovich/Law.
    It shall be inherited by child classes to customize the derivation algorithm.
    """
    @staticmethod
    def IsPublicDerivationSupported() -> bool:
        """
        Get if public derivation is supported.

        Returns:
            bool: True if supported, false otherwise.
        """
        ...
    
    @classmethod
    def CkdPriv(cls, priv_key: Bip32PrivateKey, pub_key: Bip32PublicKey, index: Bip32KeyIndex) -> Tuple[bytes, bytes]:
        """
        Derive a child key with the specified index using private derivation.

        Args:
            priv_key (Bip32PrivateKey object): Bip32PrivateKey object
            pub_key (Bip32PublicKey object)  : Bip32PublicKey object
            index (Bip32KeyIndex object)     : Key index

        Returns:
            tuple[bytes, bytes]: Private key bytes (index 0) and chain code bytes (index 1)

        Raises:
            Bip32KeyError: If the index results in an invalid key
        """
        ...
    
    @classmethod
    def CkdPub(cls, pub_key: Bip32PublicKey, index: Bip32KeyIndex) -> Tuple[Union[bytes, IPoint], bytes]:
        """
        Derive a child key with the specified index using public derivation.

        Args:
            pub_key (Bip32PublicKey object): Bip32PublicKey object
            index (Bip32KeyIndex object)   : Key index

        Returns:
            tuple[bytes or IPoint, bytes]: Public key bytes or point (index 0) and chain code bytes (index 1)

        Raises:
            Bip32KeyError: If the index results in an invalid key
        """
        ...
    


