"""
This type stub file was generated by pyright.
"""

from bip_utils.bip.bip32.base import Bip32Base
from bip_utils.ecc import EllipticCurveTypes

"""Module for keys derivation based on ed25519 curve as defined by BIP32 Khovratovich/Law."""
class Bip32KholawEd25519(Bip32Base):
    """
    BIP32 Khovratovich/Law ed25519 class.
    It allows master keys generation and keys derivation using ed25519 curve.
    """
    @staticmethod
    def CurveType() -> EllipticCurveTypes:
        """
        Return the elliptic curve type.

        Returns:
            EllipticCurveTypes: Curve type
        """
        ...
    


Bip32Ed25519Kholaw = Bip32KholawEd25519
