"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import Tuple

"""Module for BIP32 SLIP-0010 keys derivation."""
class IBip32MstKeyGenerator(ABC):
    """Interface for generic BIP32 master key generator."""
    @classmethod
    @abstractmethod
    def GenerateFromSeed(cls, seed_bytes: bytes) -> Tuple[bytes, bytes]:
        """
        Generate a master key from the specified seed.

        Args:
            seed_bytes (bytes): Seed bytes

        Returns:
            tuple[bytes, bytes]: Private key bytes (index 0) and chain code bytes (index 1)

        Raises:
            Bip32KeyError: If the seed is not suitable for master key generation
            ValueError: If seed length is not valid
        """
        ...
    


