"""
This type stub file was generated by pyright.
"""

from typing import Tuple
from bip_utils.bip.bip32 import IBip32MstKeyGenerator

"""
Module for Cardano Icarus master key generation.

References:
    https://input-output-hk.github.io/cardano-wallet/concepts/master-key-generation
    https://cips.cardano.org/cips/cip3/icarus.md
"""
class CardanoIcarusMasterKeyGeneratorConst:
    """Class container for Cardano Icarus master key generator constants."""
    PBKDF2_PASSWORD: str = ...
    PBKDF2_ROUNDS: int = ...
    PBKDF2_OUT_BYTE_LEN: int = ...


class CardanoIcarusMstKeyGenerator(IBip32MstKeyGenerator):
    """
    Cardano Icarus master key generator class.
    It allows master keys generation in according to Cardano Icarus.
    """
    @classmethod
    def GenerateFromSeed(cls, seed_bytes: bytes) -> Tuple[bytes, bytes]:
        """
        Generate a master key from the specified seed.

        Args:
            seed_bytes (bytes): Seed bytes

        Returns:
            tuple[bytes, bytes]: Private key bytes (index 0) and chain code bytes (index 1)

        Raises:
            Bip32KeyError: If the seed is not suitable for master key generation
            ValueError: If seed length is not valid
        """
        ...
    


