"""
This type stub file was generated by pyright.
"""

from bip_utils.bip.bip32 import Bip32Base
from bip_utils.ecc import EllipticCurveTypes

"""Module for keys derivation based for Cardano Byron (legacy)."""
class CardanoByronLegacyBip32(Bip32Base):
    """
    Cardano Byron legacy BIP32 class.
    It allows master keys generation and keys derivation for Cardano-Byron (legacy, used by old Daedalus).
    Derivation based on BIP32 ed25519 Khovratovich/Law with a different algorithm for master key generation and
    keys derivation.
    """
    @staticmethod
    def CurveType() -> EllipticCurveTypes:
        """
        Return the elliptic curve type.

        Returns:
            EllipticCurveTypes: Curve type
        """
        ...
    


