"""
This type stub file was generated by pyright.
"""

"""Module for mnemonic exceptions."""
class MnemonicChecksumError(Exception):
    """Exception in case of checksum error."""
    ...


