"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import Dict, List, Optional, Tuple
from bip_utils.utils.mnemonic.mnemonic import Mnemonic, MnemonicLanguages
from bip_utils.utils.typing import Literal

"""Module containing common utility classes for mnemonic."""
class MnemonicUtils:
    """Class container for mnemonic utility functions."""
    @staticmethod
    def BytesChunkToWords(bytes_chunk: bytes, words_list: MnemonicWordsList, endianness: Literal[little, big]) -> List[str]:
        """
        Get words from a bytes chunk.

        Args:
            bytes_chunk (bytes)                  : Bytes chunk
            words_list (MnemonicWordsList object): Mnemonic list
            endianness ("big" or "little")       : Bytes endianness

        Returns:
            list[str]: 3 word indexes
        """
        ...
    
    @staticmethod
    def WordsToBytesChunk(word1: str, word2: str, word3: str, words_list: MnemonicWordsList, endianness: Literal[little, big]) -> bytes:
        """
        Get bytes chunk from words.

        Args:
            word1 (str)                          : Word 1
            word2 (str)                          : Word 2
            word3 (str)                          : Word 3
            words_list (MnemonicWordsList object): Mnemonic list
            endianness ("big" or "little")       : Bytes endianness

        Returns:
            bytes: Bytes chunk
        """
        ...
    


class MnemonicWordsList:
    """Mnemonic words list class."""
    m_idx_to_words: List[str]
    m_words_to_idx: Dict[str, int]
    def __init__(self, words_list: List[str]) -> None:
        """
        Construct class.

        Args:
            words_list (list[str]): Words list
        """
        ...
    
    def Length(self) -> int:
        """
        Get the length of the words list.

        Returns:
            int: Words list length
        """
        ...
    
    def GetWordIdx(self, word: str) -> int:
        """
        Get the index of the specified word.

        Args:
            word (str): Word to be searched

        Returns:
            int: Word index

        Raises:
            ValueError: If the word is not found
        """
        ...
    
    def GetWordAtIdx(self, word_idx: int) -> str:
        """
        Get the word at the specified index.

        Args:
            word_idx (int): Word index

        Returns:
            str: Word at the specified index
        """
        ...
    


class MnemonicWordsListFileReader:
    """
    Mnemonic words list file reader class.
    It reads the words list from a file.
    """
    @staticmethod
    def LoadFile(file_path: str, words_num: int) -> MnemonicWordsList:
        """
        Load words list file correspondent to the specified language.

        Args:
            file_path (str): File name
            words_num (int): Number of expected words

        Returns:
            MnemonicWordsList: MnemonicWordsList object

        Raises:
            ValueError: If loaded words list is not valid
        """
        ...
    


class MnemonicWordsListGetterBase(ABC):
    """Mnemonic words list getter base class."""
    m_words_lists: Dict[MnemonicLanguages, MnemonicWordsList]
    __instance: Optional[MnemonicWordsListGetterBase] = ...
    def __init__(self) -> None:
        """Construct class."""
        ...
    
    @abstractmethod
    def GetByLanguage(self, lang: MnemonicLanguages) -> MnemonicWordsList:
        """
        Get words list by language.
        Words list of a specific language are loaded from file only the first time they are requested.

        Args:
            lang (MnemonicLanguages): Language

        Returns:
            MnemonicWordsList object: MnemonicWordsList object

        Raises:
            TypeError: If the language is not of the correct enumerative
            ValueError: If loaded words list is not valid
        """
        ...
    
    @classmethod
    def Instance(cls) -> MnemonicWordsListGetterBase:
        """
        Get the global class instance.

        Returns:
            MnemonicWordsListGetterBase object: MnemonicWordsListGetterBase object
        """
        ...
    


class MnemonicWordsListFinderBase(ABC):
    """
    Mnemonic words list finder base class.
    It automatically finds the correct words list from a mnemonic.
    """
    @classmethod
    @abstractmethod
    def FindLanguage(cls, mnemonic: Mnemonic) -> Tuple[MnemonicWordsList, MnemonicLanguages]:
        """
        Automatically find the language of the specified mnemonic and get the correct MnemonicWordsList class for it.

        Args:
            mnemonic (Mnemonic object): Mnemonic object

        Returns:
           tuple[MnemonicWordsList, MnemonicLanguages]: MnemonicWordsList object (index 0), mnemonic language (index 1)

        Raises:
            ValueError: If the mnemonic language cannot be found
        """
        ...
    


