"""
This type stub file was generated by pyright.
"""

"""Module with BIP32 utility functions."""
class Bip32Utils:
    """
    BIP32 utility class.
    It contains some helper methods for Bip32 indexes.

    Deprecated: only for compatibility, methods were moved to Bip32KeyIndex.
    """
    @staticmethod
    def HardenIndex(index: int) -> int:
        """
        Harden the specified index and return it.

        Args:
            index (int): Index

        Returns:
            int: Hardened index
        """
        ...
    
    @staticmethod
    def UnhardenIndex(index: int) -> int:
        """
        Unharden the specified index and return it.

        Args:
            index (int): Index

        Returns:
            int: Unhardened index
        """
        ...
    
    @staticmethod
    def IsHardenedIndex(index: int) -> bool:
        """
        Get if the specified index is hardened.

        Args:
            index (int): Index

        Returns:
            bool: True if hardened, false otherwise
        """
        ...
    


