"""
This type stub file was generated by pyright.
"""

"""Module for BIP32 net version class."""
class Bip32KeyNetVersionsConst:
    """Class container for BIP32 key net versions constants."""
    KEY_NET_VERSION_BYTE_LEN: int = ...


class Bip32KeyNetVersions:
    """
    BIP32 key net versions class.
    It represents a BIP32 key net versions.
    """
    m_pub_net_ver: bytes
    m_priv_net_ver: bytes
    def __init__(self, pub_net_ver: bytes, priv_net_ver: bytes) -> None:
        """
        Construct class.

        Args:
            pub_net_ver (bytes) : Public net version
            priv_net_ver (bytes): Private net version
        """
        ...
    
    @staticmethod
    def Length() -> int:
        """
        Get the key net version length.

        Returns:
            int: Key net version length
        """
        ...
    
    def Public(self) -> bytes:
        """
        Get public net version.

        Returns:
            bytes: Public net version
        """
        ...
    
    def Private(self) -> bytes:
        """
        Get private net version.

        Returns:
            bytes: Private net version
        """
        ...
    


