"""
This type stub file was generated by pyright.
"""

from bip_utils.bip.bip32.bip32_key_net_ver import Bip32KeyNetVersions

"""Module with BIP32 constants."""
class Bip32Const:
    """Class container for BIP32 constants."""
    MAIN_NET_KEY_NET_VERSIONS: Bip32KeyNetVersions = ...
    TEST_NET_KEY_NET_VERSIONS: Bip32KeyNetVersions = ...
    KHOLAW_KEY_NET_VERSIONS: Bip32KeyNetVersions = ...


