"""
This type stub file was generated by pyright.
"""

from typing import Union
from bip_utils.utils.misc import DataBytes
from bip_utils.utils.typing import Literal

"""Module with helper classes for BIP32 key data."""
class Bip32KeyDataConst:
    """Class container for BIP32 key data constants."""
    CHAINCODE_BYTE_LEN: int = ...
    DEPTH_BYTE_LEN: int = ...
    FINGERPRINT_BYTE_LEN: int = ...
    FINGERPRINT_MASTER_KEY: bytes = ...
    KEY_INDEX_BYTE_LEN: int = ...
    KEY_INDEX_MAX_VAL: int = ...
    KEY_INDEX_HARDENED_BIT_NUM: int = ...


class Bip32ChainCode(DataBytes):
    """
    BIP32 chaincode class.
    It represents a BIP32 chaincode.
    """
    def __init__(self, chaincode: bytes = ...) -> None:
        """
        Construct class.

        Args:
            chaincode (bytes, optional): Fingerprint bytes (default: zero)

        Raises:
            ValueError: If the chain code length is not valid
        """
        ...
    
    @staticmethod
    def FixedLength() -> int:
        """
        Get the fixed length in bytes.

        Returns:
            int: Length in bytes
        """
        ...
    


class Bip32FingerPrint(DataBytes):
    """
    BIP32 fingerprint class.
    It represents a BIP32 fingerprint.
    """
    def __init__(self, fprint: bytes = ...) -> None:
        """
        Construct class.

        Args:
            fprint (bytes, optional): Fingerprint bytes (default: master key)

        Raises:
            ValueError: If the chain code length is not valid
        """
        ...
    
    @staticmethod
    def FixedLength() -> int:
        """
        Get the fixed length in bytes.

        Returns:
            int: Length in bytes
        """
        ...
    
    def IsMasterKey(self) -> bool:
        """
        Get if the fingerprint corresponds to a master key.

        Returns:
            bool: True if it corresponds to a master key, false otherwise
        """
        ...
    


class Bip32Depth:
    """
    BIP32 depth class.
    It represents a BIP32 depth.
    """
    m_depth: int
    def __init__(self, depth: int) -> None:
        """
        Construct class.

        Args:
            depth (int): Depth

        Raises:
            ValueError: If the depth value is not valid
        """
        ...
    
    @staticmethod
    def FixedLength() -> int:
        """
        Get the fixed length in bytes.

        Returns:
            int: Length in bytes
        """
        ...
    
    def Increase(self) -> Bip32Depth:
        """
        Get a new object with increased depth.

        Returns:
            Bip32Depth object: Bip32Depth object
        """
        ...
    
    def ToBytes(self) -> bytes:
        """
        Get the depth as bytes.

        Returns:
            bytes: Depth bytes
        """
        ...
    
    def ToInt(self) -> int:
        """
        Get the depth as integer.

        Returns:
            int: Depth index
        """
        ...
    
    def __int__(self) -> int:
        """
        Get the depth as integer.

        Returns:
            int: Depth index
        """
        ...
    
    def __bytes__(self) -> bytes:
        """
        Get the depth as bytes.

        Returns:
            bytes: Depth bytes
        """
        ...
    
    def __eq__(self, other: object) -> bool:
        """
        Equality operator.

        Args:
            other (int or Bip32Depth object): Other object to compare

        Returns:
            bool: True if equal false otherwise

        Raises:
            TypeError: If the other object is not of the correct type
        """
        ...
    
    def __gt__(self, other: Union[int, Bip32Depth]) -> bool:
        """
        Greater than operator.

        Args:
            other (int or Bip32Depth object): Other value to compare

        Returns:
            bool: True if greater false otherwise
        """
        ...
    
    def __lt__(self, other: Union[int, Bip32Depth]) -> bool:
        """
        Lower than operator.

        Args:
            other (int or Bip32Depth object): Other value to compare

        Returns:
            bool: True if lower false otherwise
        """
        ...
    


class Bip32KeyIndex:
    """
    BIP32 key index class.
    It represents a BIP32 key index.
    """
    m_idx: int
    @staticmethod
    def HardenIndex(index: int) -> int:
        """
        Harden the specified index and return it.

        Args:
            index (int): Index

        Returns:
            int: Hardened index
        """
        ...
    
    @staticmethod
    def UnhardenIndex(index: int) -> int:
        """
        Unharden the specified index and return it.

        Args:
            index (int): Index

        Returns:
            int: Unhardened index
        """
        ...
    
    @staticmethod
    def IsHardenedIndex(index: int) -> bool:
        """
        Get if the specified index is hardened.

        Args:
            index (int): Index

        Returns:
            bool: True if hardened, false otherwise
        """
        ...
    
    @classmethod
    def FromBytes(cls, index_bytes: bytes) -> Bip32KeyIndex:
        """
        Construct class from bytes.

        Args:
            index_bytes (bytes): Key index bytes

        Returns:
            Bip32KeyIndex object: Bip32KeyIndex object

        Raises:
            ValueError: If the index is not valid
        """
        ...
    
    def __init__(self, idx: int) -> None:
        """
        Construct class.

        Args:
            idx (int): Key index

        Raises:
            ValueError: If the index value is not valid
        """
        ...
    
    @staticmethod
    def FixedLength() -> int:
        """
        Get the fixed length in bytes.

        Returns:
            int: Length in bytes
        """
        ...
    
    def Harden(self) -> Bip32KeyIndex:
        """
        Get a new Bip32KeyIndex object with the current key index hardened.

        Returns:
            Bip32KeyIndex object: Bip32KeyIndex object
        """
        ...
    
    def Unharden(self) -> Bip32KeyIndex:
        """
        Get a new Bip32KeyIndex object with the current key index unhardened.

        Returns:
            Bip32KeyIndex object: Bip32KeyIndex object
        """
        ...
    
    def IsHardened(self) -> bool:
        """
        Get if the key index is hardened.

        Returns:
            bool: True if hardened, false otherwise
        """
        ...
    
    def ToBytes(self, endianness: Literal[little, big] = ...) -> bytes:
        """
        Get the key index as bytes.

        Args:
            endianness ("big" or "little", optional): Endianness (default: big)

        Returns:
            bytes: Key bytes
        """
        ...
    
    def ToInt(self) -> int:
        """
        Get the key index as integer.

        Returns:
            int: Key index
        """
        ...
    
    def __int__(self) -> int:
        """
        Get the key index as integer.

        Returns:
            int: Key index
        """
        ...
    
    def __bytes__(self) -> bytes:
        """
        Get the key index as bytes.

        Returns:
            bytes: Key bytes
        """
        ...
    
    def __eq__(self, other: object) -> bool:
        """
        Equality operator.

        Args:
            other (int or Bip32KeyIndex object): Other value to compare

        Returns:
            bool: True if equal false otherwise

        Raises:
            TypeError: If the object is not of the correct type
        """
        ...
    


class Bip32KeyData:
    """
    BIP32 key data class.
    It contains all additional data related to a BIP32 key (e.g. depth, chain code, etc...).
    """
    m_depth: Bip32Depth
    m_index: Bip32KeyIndex
    m_chain_code: Bip32ChainCode
    m_parent_fprint: Bip32FingerPrint
    def __init__(self, depth: Union[int, Bip32Depth] = ..., index: Union[int, Bip32KeyIndex] = ..., chain_code: Union[bytes, Bip32ChainCode] = ..., parent_fprint: Union[bytes, Bip32FingerPrint] = ...) -> None:
        """
        Construct class.

        Args:
            depth (Bip32Depth object)               : Key depth
            index (Bip32KeyIndex object)            : Key index
            chain_code (Bip32ChainCode object)      : Key chain code
            parent_fprint (Bip32FingerPrint object) : Key parent fingerprint
        """
        ...
    
    def Depth(self) -> Bip32Depth:
        """
        Get current depth.

        Returns:
            Bip32Depth object: Current depth
        """
        ...
    
    def Index(self) -> Bip32KeyIndex:
        """
        Get current index.

        Returns:
            Bip32KeyIndex object: Current index
        """
        ...
    
    def ChainCode(self) -> Bip32ChainCode:
        """
        Get current chain code.

        Returns:
            Bip32ChainCode object: Chain code
        """
        ...
    
    def ParentFingerPrint(self) -> Bip32FingerPrint:
        """
        Get parent fingerprint.

        Returns:
            Bip32FingerPrint object: Parent fingerprint
        """
        ...
    


