"""
This type stub file was generated by pyright.
"""

from enum import Enum, unique

"""Module for Monero coins enum."""
@unique
class MoneroCoins(Enum):
    """Enumerative for supported Monero coins."""
    MONERO_MAINNET = ...
    MONERO_STAGENET = ...
    MONERO_TESTNET = ...


