"""
This type stub file was generated by pyright.
"""

from bip_utils.monero.conf.monero_coin_conf import MoneroCoinConf

"""Module for Monero coins configuration."""
class MoneroConf:
    """Class container for Monero configuration."""
    MainNet: MoneroCoinConf = ...
    StageNet: MoneroCoinConf = ...
    TestNet: MoneroCoinConf = ...


