"""
This type stub file was generated by pyright.
"""

from typing import Dict
from bip_utils.coin_conf import CoinConf
from bip_utils.utils.conf import CoinNames as UtilsCoinNames

"""Module with helper class for Monero coins configuration handling."""
class MoneroCoinConf:
    """Monero coin configuration class."""
    m_coin_names: UtilsCoinNames
    m_addr_net_ver: bytes
    m_int_addr_net_ver: bytes
    m_subaddr_net_ver: bytes
    m_addr_params: Dict[str, bytes]
    @classmethod
    def FromCoinConf(cls, coin_conf: CoinConf) -> MoneroCoinConf:
        """
        Construct class.

        Args:
            coin_conf (CoinConf object): Generic coin configuration object

        Returns:
            MoneroCoinConf object: MoneroCoinConf object
        """
        ...
    
    def __init__(self, coin_names: UtilsCoinNames, addr_net_ver: bytes, int_addr_net_ver: bytes, subaddr_net_ver: bytes) -> None:
        """
        Construct class.

        Args:
            coin_names (CoinNames object): Coin names
            addr_net_ver (bytes)         : Address net version
            int_addr_net_ver (bytes)     : Integrated address net version
            subaddr_net_ver (bytes)      : Subaddress net version
        """
        ...
    
    def CoinNames(self) -> UtilsCoinNames:
        """
        Get coin names.

        Returns:
            CoinNames object: CoinNames object
        """
        ...
    
    def AddrNetVersion(self) -> bytes:
        """
        Get address net version.

        Returns:
            bytes: Address net version
        """
        ...
    
    def IntegratedAddrNetVersion(self) -> bytes:
        """
        Get integrated address net version.

        Returns:
            bytes: Address net version
        """
        ...
    
    def SubaddrNetVersion(self) -> bytes:
        """
        Get subaddress net version.

        Returns:
            bytes: Subaddress net version
        """
        ...
    


