"""
This type stub file was generated by pyright.
"""

from bip_utils.bip.bip32.base import Bip32Base
from bip_utils.ecc import EllipticCurveTypes

"""Module for derivation scheme based on ed25519 curve as defined by BIP32 SLIP-0010."""
class Bip32Slip10Ed25519(Bip32Base):
    """
    BIP32 SLIP-0010 ed25519 class.
    It allows master keys generation and keys derivation using ed25519 curve.
    """
    @staticmethod
    def CurveType() -> EllipticCurveTypes:
        """
        Return the elliptic curve type.

        Returns:
            EllipticCurveTypes: Curve type
        """
        ...
    


Bip32Ed25519Slip = Bip32Slip10Ed25519
