"""
This type stub file was generated by pyright.
"""

from bip_utils.bip.bip32.base import Bip32Base
from bip_utils.ecc import EllipticCurveTypes

"""Module for derivation scheme based on nist256p1 curve as defined by BIP32 SLIP-0010."""
class Bip32Slip10Nist256p1(Bip32Base):
    """
    BIP32 SLIP-0010 nist256p1 class.
    It allows master keys generation and keys derivation using nist256p1 curve.
    """
    @staticmethod
    def CurveType() -> EllipticCurveTypes:
        """
        Return the elliptic curve type.

        Returns:
            EllipticCurveTypes: Curve type
        """
        ...
    


Bip32Nist256p1 = Bip32Slip10Nist256p1
