"""
This type stub file was generated by pyright.
"""

from bip_utils.bip.bip32.base import Bip32Base
from bip_utils.ecc import EllipticCurveTypes

"""Module for derivation scheme based on secp256k1 curve as defined by BIP32 SLIP-0010."""
class Bip32Slip10Secp256k1(Bip32Base):
    """
    BIP32 SLIP-0010 secp256k1 v.
    It allows master keys generation and keys derivation using secp256k1 curve.
    """
    @staticmethod
    def CurveType() -> EllipticCurveTypes:
        """
        Return the elliptic curve type.

        Returns:
            EllipticCurveTypes: Curve type
        """
        ...
    


Bip32Secp256k1 = Bip32Slip10Secp256k1
