"""
This type stub file was generated by pyright.
"""

from typing import Tuple
from bip_utils.bip.bip32.base import IBip32MstKeyGenerator
from bip_utils.ecc import EllipticCurveTypes

"""
Module for BIP32 SLIP-0010 master key generation.
Reference: https://github.com/satoshilabs/slips/blob/master/slip-0010.md
"""
class Bip32Slip10MstKeyGeneratorConst:
    """Class container for BIP32 SLIP-0010 master key generator constants."""
    SEED_MIN_BYTE_LEN: int = ...
    HMAC_KEY_ED25519_BYTES: bytes = ...
    HMAC_KEY_NIST256P1_BYTES: bytes = ...
    HMAC_KEY_SECP256K1_BYTES: bytes = ...


class _Bip32Slip10MstKeyGenerator:
    """
    BIP32 SLIP-0010 generic master key generator class.
    It allows master keys generation in according to BIP32 SLIP-0010.
    """
    @staticmethod
    def GenerateFromSeed(seed_bytes: bytes, hmac_key_bytes: bytes, curve_type: EllipticCurveTypes) -> Tuple[bytes, bytes]:
        """
        Generate a master key from the specified seed and return a Bip32Base object.

        Args:
            seed_bytes (bytes)                      : Seed bytes
            hmac_key_bytes (bytes)                  : HMAC key bytes

        Returns:
            Bip32Base object: Bip32Base object

        Raises:
            Bip32KeyError: If the seed is not suitable for master key generation
            ValueError: If seed length is not valid
        """
        ...
    


class Bip32Slip10Ed2519MstKeyGenerator(IBip32MstKeyGenerator):
    """
    BIP32 SLIP-0010 ed25519 master key generator class.
    It allows master keys generation in according to BIP32 SLIP-0010 for ed25519 curve.
    """
    @classmethod
    def GenerateFromSeed(cls, seed_bytes: bytes) -> Tuple[bytes, bytes]:
        """
        Generate a master key from the specified seed.

        Args:
            seed_bytes (bytes): Seed bytes

        Returns:
            tuple[bytes, bytes]: Private key bytes (index 0) and chain code bytes (index 1)

        Raises:
            Bip32KeyError: If the seed is not suitable for master key generation
            ValueError: If seed length is not valid
        """
        ...
    


class Bip32Slip10Nist256p1MstKeyGenerator(IBip32MstKeyGenerator):
    """
    BIP32 SLIP-0010 nist256p1 master key generator class.
    It allows master keys generation in according to BIP32 SLIP-0010 for nist256p1 curve.
    """
    @classmethod
    def GenerateFromSeed(cls, seed_bytes: bytes) -> Tuple[bytes, bytes]:
        """
        Generate a master key from the specified seed.

        Args:
            seed_bytes (bytes): Seed bytes

        Returns:
            tuple[bytes, bytes]: Private key bytes (index 0) and chain code bytes (index 1)

        Raises:
            Bip32KeyError: If the seed is not suitable for master key generation
            ValueError: If seed length is not valid
        """
        ...
    


class Bip32Slip10Secp256k1MstKeyGenerator(IBip32MstKeyGenerator):
    """
    BIP32 SLIP-0010 secp256k1 master key generator class.
    It allows master keys generation in according to BIP32 SLIP-0010 for secp256k1 curve.
    """
    @classmethod
    def GenerateFromSeed(cls, seed_bytes: bytes) -> Tuple[bytes, bytes]:
        """
        Generate a master key from the specified seed.

        Args:
            seed_bytes (bytes): Seed bytes

        Returns:
            tuple[bytes, bytes]: Private key bytes (index 0) and chain code bytes (index 1)

        Raises:
            Bip32KeyError: If the seed is not suitable for master key generation
            ValueError: If seed length is not valid
        """
        ...
    


