"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from enum import IntEnum, unique
from functools import lru_cache
from typing import Union
from bip_utils.bip.bip32 import Bip32Base, Bip32KeyData
from bip_utils.bip.bip44_base.bip44_keys import Bip44PrivateKey, Bip44PublicKey
from bip_utils.bip.conf.common import BipCoinConf, BipCoins
from bip_utils.ecc import IPrivateKey, IPublicKey

"""Module with BIP44 base class."""
@unique
class Bip44Changes(IntEnum):
    """Enumerative for BIP44 changes."""
    CHAIN_EXT = ...
    CHAIN_INT = ...


@unique
class Bip44Levels(IntEnum):
    """Enumerative for BIP44 levels."""
    MASTER = ...
    PURPOSE = ...
    COIN = ...
    ACCOUNT = ...
    CHANGE = ...
    ADDRESS_INDEX = ...


class Bip44Base(ABC):
    """
    BIP44 base class.
    It allows coin, account, chain and address keys generation in according to BIP44 or its extensions.
    The class is meant to be derived by classes implementing BIP44 or its extensions.
    """
    m_bip32_obj: Bip32Base
    m_coin_conf: BipCoinConf
    def __init__(self, bip32_obj: Bip32Base, coin_conf: BipCoinConf) -> None:
        """
        Construct class.

        Args:
            bip32_obj (Bip32Base object): Bip32Base object
            coin_conf (BipCoinConf)     : BipCoinConf object

        Returns:
            Bip44DepthError: If the Bip32 object depth is not valid
        """
        ...
    
    @lru_cache()
    def PublicKey(self) -> Bip44PublicKey:
        """
        Return the public key.

        Returns:
            Bip44PublicKey object: Bip44PublicKey object
        """
        ...
    
    @lru_cache()
    def PrivateKey(self) -> Bip44PrivateKey:
        """
        Return the private key.

        Returns:
            Bip44PrivateKey object: Bip44PrivateKey object

        Raises:
            Bip32KeyError: If the Bip32 object is public-only
        """
        ...
    
    def Bip32Object(self) -> Bip32Base:
        """
        Return the BIP32 object.

        Returns:
            Bip32Base object: Bip32Base object
        """
        ...
    
    def CoinConf(self) -> BipCoinConf:
        """
        Get coin configuration.

        Returns:
            BipCoinConf object: BipCoinConf object
        """
        ...
    
    def IsPublicOnly(self) -> bool:
        """
        Get if it's public-only.

        Returns:
            bool: True if public-only, false otherwise
        """
        ...
    
    def Level(self) -> Bip44Levels:
        """
        Return the current level.

        Returns:
            Bip44Levels: Current level
        """
        ...
    
    def IsLevel(self, level: Bip44Levels) -> bool:
        """
        Return if the current level is the specified one.

        Args:
            level (Bip44Levels): Level to be checked

        Returns:
            bool: True if it's the specified level, false otherwise

        Raises:
            TypeError: If the level index is not a Bip44Levels enum
        """
        ...
    
    def DeriveDefaultPath(self) -> Bip44Base:
        """
        Derive the default coin path and return a new Bip44Base object.

        Returns:
            Bip44Base object: Bip44Base object

        Raises:
            Bip44DepthError: If the current depth is not suitable for deriving keys
            Bip32KeyError: If the derivation results in an invalid key
        """
        ...
    
    @classmethod
    @abstractmethod
    def FromSeed(cls, seed_bytes: bytes, coin_type: BipCoins) -> Bip44Base:
        """
        Create a Bip44Base object from the specified seed (e.g. BIP39 seed).
        The test net flag is automatically set when the coin is derived. However, if you want to get the correct master
        or purpose keys, you have to specify here if it's a test net.

        Args:
            seed_bytes (bytes)  : Seed bytes
            coin_type (BipCoins): Coin type (the type depends on the specific child class)

        Returns:
            Bip44Base object: Bip44Base object

        Raises:
            TypeError: If coin type is not of the correct type
            ValueError: If the seed is too short
            Bip32KeyError: If the seed is not suitable for master key generation
        """
        ...
    
    @classmethod
    @abstractmethod
    def FromExtendedKey(cls, ex_key_str: str, coin_type: BipCoins) -> Bip44Base:
        """
        Create a Bip44Base object from the specified extended key.

        Args:
            ex_key_str (str)    : Extended key string
            coin_type (BipCoins): Coin type (the type depends on the specific child class)

        Returns:
            Bip44Base object: Bip44Base object

        Raises:
            TypeError: If coin type is not of the correct type
            Bip32KeyError: If the extended key is not valid
        """
        ...
    
    @classmethod
    @abstractmethod
    def FromPrivateKey(cls, priv_key: Union[bytes, IPrivateKey], coin_type: BipCoins, key_data: Bip32KeyData) -> Bip44Base:
        """
        Create a Bip44Base object from the specified private key and derivation data.
        If only the private key bytes are specified, the key will be considered a master key with
        the chain code set to zero, since there is no way to recover the key derivation data.

        Args:
            priv_key (bytes or IPrivateKey): Private key
            coin_type (BipCoins)           : Coin type, shall be a Bip44Coins enum
            key_data (Bip32KeyData object) : Key data

        Returns:
            Bip44Base object: Bip44Base object

        Raises:
            TypeError: If coin type is not a Bip44Coins enum
            Bip32KeyError: If the key is not valid
        """
        ...
    
    @classmethod
    @abstractmethod
    def FromPublicKey(cls, pub_key: Union[bytes, IPublicKey], coin_type: BipCoins, key_data: Bip32KeyData) -> Bip44Base:
        """
        Create a Bip44Base object from the specified public key and derivation data.
        If only the public key bytes are specified, the key will be considered an account key with
        the chain code set to zero, since there is no way to recover the key derivation data.

        Args:
            pub_key (bytes or IPublicKey) : Public key
            coin_type (BipCoins)          : Coin type, shall be a Bip44Coins enum
            key_data (Bip32KeyData object): Key data

        Returns:
            Bip44Base object: Bip44Base object

        Raises:
            TypeError: If coin type is not a Bip44Coins enum
            Bip32KeyError: If the key is not valid
        """
        ...
    
    @abstractmethod
    def Purpose(self) -> Bip44Base:
        """
        Derive a child key from the purpose and return a new Bip44Base object.

        Returns:
            Bip44Base object: Bip44Base object

        Raises:
            Bip44DepthError: If current depth is not suitable for deriving keys
            Bip32KeyError: If the derivation results in an invalid key
        """
        ...
    
    @abstractmethod
    def Coin(self) -> Bip44Base:
        """
        Derive a child key from the coin type specified at construction and return a new Bip44Base object.

        Returns:
            Bip44Base object: Bip44Base object

        Raises:
            Bip44DepthError: If current depth is not suitable for deriving keys
            Bip32KeyError: If the derivation results in an invalid key
        """
        ...
    
    @abstractmethod
    def Account(self, acc_idx: int) -> Bip44Base:
        """
        Derive a child key from the specified account index and return a new Bip44Base object.

        Args:
            acc_idx (int): Account index

        Returns:
            Bip44Base object: Bip44Base object

        Raises:
            Bip44DepthError: If current depth is not suitable for deriving keys
            Bip32KeyError: If the derivation results in an invalid key
        """
        ...
    
    @abstractmethod
    def Change(self, change_type: Bip44Changes) -> Bip44Base:
        """
        Derive a child key from the specified change type and return a new Bip44Base object.

        Args:
            change_type (Bip44Changes): Change type, must a Bip44Changes enum

        Returns:
            Bip44Base object: Bip44Base object

        Raises:
            TypeError: If change type is not a Bip44Changes enum
            Bip44DepthError: If current depth is not suitable for deriving keys
            Bip32KeyError: If the derivation results in an invalid key
        """
        ...
    
    @abstractmethod
    def AddressIndex(self, addr_idx: int) -> Bip44Base:
        """
        Derive a child key from the specified address index and return a new Bip44Base object.

        Args:
            addr_idx (int): Address index

        Returns:
            Bip44Base object: Bip44Base object

        Raises:
            Bip44DepthError: If current depth is not suitable for deriving keys
            Bip32KeyError: If the derivation results in an invalid key
        """
        ...
    
    @staticmethod
    @abstractmethod
    def SpecName() -> str:
        """
        Get specification name.

        Returns:
            str: Specification name
        """
        ...
    


