"""
This type stub file was generated by pyright.
"""

from typing import Union
from bip_utils.ecc import IPublicKey
from bip_utils.wif import WifPubKeyModes

"""Module with BIP38 utility functions."""
Bip38PubKeyModes = WifPubKeyModes
class Bip38AddrConst:
    """Class container for BIP38 address constants."""
    ADDR_HASH_LEN: int = ...


class Bip38Addr:
    """Class for BIP38 address computation."""
    @staticmethod
    def AddressHash(pub_key: Union[bytes, IPublicKey], pub_key_mode: Bip38PubKeyModes) -> bytes:
        """
        Compute the address hash as specified in BIP38.

        Args:
            pub_key (bytes or IPublicKey)  : Public key bytes or object
            pub_key_mode (Bip38PubKeyModes): Public key mode

        Returns:
            bytes: Address hash

        Raises:
            TypeError: If the public key is not a Secp256k1PublicKey
            ValueError: If the public key bytes are not valid
        """
        ...
    


