"""
This type stub file was generated by pyright.
"""

import stem.response

class GetInfoResponse(stem.response.ControlMessage):
  """
  Reply for a GETINFO query.

  :var dict entries: mapping between the queried options and their bytes values
  """
  ...


