"""
This type stub file was generated by pyright.
"""

from typing import Any
from bip_utils.substrate.scale.substrate_scale_enc_base import SubstrateScaleEncoderBase

"""Module for Substrate SCALE encoding for bytes."""
class SubstrateScaleBytesEncoder(SubstrateScaleEncoderBase):
    """Substrate SCALE encoding class for bytes."""
    @classmethod
    def Encode(cls, value: Any) -> bytes:
        """
        Encode the specified value to bytes.

        Args:
            value (any): Value to be encoded

        Returns:
            bytes: Encoded value
        """
        ...
    


