"""
This type stub file was generated by pyright.
"""

from bip_utils.ecc.common.ipoint import IPoint

"""Module with ed25519-kholaw constants."""
class Ed25519KholawConst:
    """Class container for Ed25519-Kholaw constants."""
    NAME: str = ...
    CURVE_ORDER: int = ...
    GENERATOR: IPoint = ...


