"""
This type stub file was generated by pyright.
"""

from bip_utils.ecc.common.ipoint import IPoint

"""Module for ed25519-blake2b constants."""
class Ed25519Blake2bConst:
    """Class container for Ed25519-Blake2b constants."""
    NAME: str = ...
    CURVE_ORDER: int = ...
    GENERATOR: IPoint = ...


