"""
This type stub file was generated by pyright.
"""

from bip_utils.ecc.common.ipoint import IPoint

"""Module with ed25519-monero constants."""
class Ed25519MoneroConst:
    """Class container for Ed25519-Monero constants."""
    NAME: str = ...
    CURVE_ORDER: int = ...
    GENERATOR: IPoint = ...


