"""
This type stub file was generated by pyright.
"""

from typing import Dict
from bip_utils.coin_conf import CoinConf
from bip_utils.utils.conf import CoinNames as UtilsCoinNames

"""Module with helper class for Substrate coins configuration handling."""
class SubstrateCoinConf:
    """Substrate coin configuration class."""
    m_coin_names: UtilsCoinNames
    m_ss58_format: int
    m_addr_params: Dict[str, int]
    @classmethod
    def FromCoinConf(cls, coin_conf: CoinConf) -> SubstrateCoinConf:
        """
        Construct class.

        Args:
            coin_conf (CoinConf object): Generic coin configuration object

        Returns:
            SubstrateCoinConf object: SubstrateCoinConf object
        """
        ...
    
    def __init__(self, coin_names: UtilsCoinNames, ss58_format: int) -> None:
        """
        Construct class.

        Args:
            coin_names (CoinNames object): Coin names
            ss58_format (int)            : SS58 format
        """
        ...
    
    def CoinNames(self) -> UtilsCoinNames:
        """
        Get coin names.

        Returns:
            CoinNames object: CoinNames object
        """
        ...
    
    def SS58Format(self) -> int:
        """
        Get SS58 format.

        Returns:
            int: SS58 format
        """
        ...
    
    def AddrParams(self) -> Dict[str, int]:
        """
        Get the address parameters.

        Returns:
            dict: Address parameters
        """
        ...
    


