"""
This type stub file was generated by pyright.
"""

from enum import IntEnum, unique
from typing import List, Union
from bip_utils.utils.mnemonic import EntropyGenerator

"""Module for BIP39 mnemonic entropy generation."""
@unique
class Bip39EntropyBitLen(IntEnum):
    """Enumerative for BIP39 entropy bit lengths."""
    BIT_LEN_128 = ...
    BIT_LEN_160 = ...
    BIT_LEN_192 = ...
    BIT_LEN_224 = ...
    BIT_LEN_256 = ...


class Bip39EntropyGeneratorConst:
    """Class container for BIP39 entropy generator constants."""
    ENTROPY_BIT_LEN: List[Bip39EntropyBitLen] = ...


class Bip39EntropyGenerator(EntropyGenerator):
    """
    BIP39 entropy generator class.
    It generates random entropy bytes with the specified length.
    """
    def __init__(self, bit_len: Union[int, Bip39EntropyBitLen]) -> None:
        """
        Construct class.

        Args:
            bit_len (int or Bip39EntropyBitLen): Entropy length in bits

        Raises:
            ValueError: If the bit length is not valid
        """
        ...
    
    @staticmethod
    def IsValidEntropyBitLen(bit_len: Union[int, Bip39EntropyBitLen]) -> bool:
        """
        Get if the specified entropy bit length is valid.

        Args:
            bit_len (int or Bip39EntropyBitLen): Entropy length in bits

        Returns:
            bool: True if valid, false otherwise
        """
        ...
    
    @staticmethod
    def IsValidEntropyByteLen(byte_len: int) -> bool:
        """
        Get if the specified entropy byte length is valid.

        Args:
            byte_len (int): Entropy length in bytes

        Returns:
            bool: True if valid, false otherwise
        """
        ...
    


