"""
This type stub file was generated by pyright.
"""

from typing import Optional
from bip_utils.bip.bip39.bip39_mnemonic import Bip39Languages
from bip_utils.utils.mnemonic import MnemonicValidator

"""Module for BIP39 mnemonic validation."""
class Bip39MnemonicValidator(MnemonicValidator):
    """
    BIP39 mnemonic validator class.
    It validates a mnemonic phrase.
    """
    def __init__(self, lang: Optional[Bip39Languages] = ...) -> None:
        """
        Construct class.

        Args:
            lang (Bip39Languages, optional): Language, None for automatic detection
        """
        ...
    


