"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import Optional, Union
from bip_utils.bip.bip39.bip39_mnemonic import Bip39Languages
from bip_utils.utils.mnemonic import Mnemonic

"""Module with interface for BIP39 seed generation classes."""
class IBip39SeedGenerator(ABC):
    """BIP39 seed generator interface."""
    @abstractmethod
    def __init__(self, mnemonic: Union[str, Mnemonic], lang: Optional[Bip39Languages]) -> None:
        """
        Construct class.

        Args:
            mnemonic (str or Mnemonic object): Mnemonic
            lang (Bip39Languages, optional)  : Language, None for automatic detection

        Raises:
            ValueError: If the mnemonic is not valid
        """
        ...
    
    @abstractmethod
    def Generate(self, passphrase: str) -> bytes:
        """
        Generate the seed using the specified passphrase.

        Args:
            passphrase (str, optional): Passphrase, empty if not specified

        Returns:
            bytes: Generated seed
        """
        ...
    


