"""
This type stub file was generated by pyright.
"""

from enum import IntEnum, unique
from typing import List
from bip_utils.bip.bip39 import Bip39Mnemonic
from bip_utils.utils.mnemonic import MnemonicLanguages

"""Module for Algorand mnemonic."""
@unique
class AlgorandWordsNum(IntEnum):
    """Enumerative for Algorand words number."""
    WORDS_NUM_25 = ...


@unique
class AlgorandLanguages(MnemonicLanguages):
    """Enumerative for Algorand languages."""
    ENGLISH = ...


class AlgorandMnemonicConst:
    """Class container for Algorand mnemonic constants."""
    MNEMONIC_WORD_NUM: List[AlgorandWordsNum] = ...
    CHECKSUM_BYTE_LEN: int = ...


class AlgorandMnemonic(Bip39Mnemonic):
    """Algorand mnemonic class."""
    ...


