"""
This type stub file was generated by pyright.
"""

from typing import Optional, Union
from bip_utils.algorand.mnemonic.algorand_mnemonic import AlgorandLanguages
from bip_utils.utils.mnemonic import Mnemonic, MnemonicDecoderBase

"""
Module for Algorand mnemonic decoding.
Reference: https://github.com/algorand/py-algorand-sdk
"""
class AlgorandMnemonicDecoder(MnemonicDecoderBase):
    """
    Algorand mnemonic decoder class.
    It decodes a mnemonic phrase to bytes.
    """
    def __init__(self, lang: Optional[AlgorandLanguages] = ...) -> None:
        """
        Construct class.
        Language is set to English by default because Algorand mnemonic only support one language,
        so it's useless (and slower) to automatically detect the language.

        Args:
            lang (AlgorandLanguages, optional): Language, None for automatic detection

        Raises:
            TypeError: If the language is not a AlgorandLanguages enum
            ValueError: If loaded words list is not valid
        """
        ...
    
    def Decode(self, mnemonic: Union[str, Mnemonic]) -> bytes:
        """
        Decode a mnemonic phrase to bytes (no checksum).

        Args:
            mnemonic (str or Mnemonic object): Mnemonic

        Returns:
            bytes: Decoded bytes

        Raises:
            MnemonicChecksumError: If checksum is not valid
            ValueError: If mnemonic is not valid
        """
        ...
    


