"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Union

"""Module with some algorithm utility functions."""
class AlgoUtils:
    """Class container for algorithm utility functions."""
    @staticmethod
    def BinarySearch(arr: List, elem: Any) -> int:
        """
        Binary search algorithm simply implemented by using the bisect library.

        Args:
            arr (list): list of elements
            elem (any): element to be searched

        Returns:
            int: First index of the element, -1 if not found
        """
        ...
    
    @staticmethod
    def Decode(data: Union[bytes, str], encoding: str = ...) -> str:
        """
        Decode from bytes.

        Args:
            data (str or bytes): Data
            encoding (str)     : Encoding type

        Returns:
            str: String encoded to bytes

        Raises:
            TypeError: If the data is neither string nor bytes
        """
        ...
    
    @staticmethod
    def Encode(data: Union[bytes, str], encoding: str = ...) -> bytes:
        """
        Encode to bytes.

        Args:
            data (str or bytes): Data
            encoding (str)     : Encoding type

        Returns:
            bytes: String encoded to bytes

        Raises:
            TypeError: If the data is neither string nor bytes
        """
        ...
    
    @staticmethod
    def IsStringMixed(data_str: str) -> bool:
        """
        Get if the specified string is in mixed case.

        Args:
            data_str (str): string

        Returns:
            bool: True if mixed case, false otherwise
        """
        ...
    


