"""
This type stub file was generated by pyright.
"""

from enum import IntEnum, unique
from typing import Dict, List, Sequence

"""
Module for CBOR decoding/encoding indefinite length arrays.
Indefinite length arrays are encoded without writing the array length, so elements shall be read until
the termination byte is found.

NOTE: encoding of values greater than 2^64 is not supported.
"""
@unique
class CborIds(IntEnum):
    """Enumerative for CBOR identifiers."""
    UINT8 = ...
    UINT16 = ...
    UINT32 = ...
    UINT64 = ...
    INDEF_LEN_ARRAY_START = ...
    INDEF_LEN_ARRAY_END = ...


class CborIndefiniteLenArrayConst:
    """Class container for CBOR indefinite length arrays constants."""
    UINT_IDS_TO_BYTE_LEN: Dict[int, int] = ...


class CborIndefiniteLenArrayDecoder:
    """
    CBOR indefinite length arrays decoder.
    It decodes bytes back to array.
    """
    @staticmethod
    def Decode(enc_bytes: bytes) -> List[int]:
        """
        CBOR-decode the specified bytes.

        Args:
            enc_bytes (bytes): Encoded bytes

        Returns:
            list[int]: List of integers

        Raises:
            ValueError: If encoding is not valid
        """
        ...
    


class CborIndefiniteLenArrayEncoder:
    """
    CBOR indefinite length arrays encoder.
    It encodes indefinite length arrays to bytes.
    """
    @staticmethod
    def Encode(int_seq: Sequence[int]) -> bytes:
        """
        CBOR-encode the specified elements.

        Args:
            int_seq (sequence[int]): Collection of integers

        Returns:
            bytes: CBOR-encoded bytes
        """
        ...
    


