"""
This type stub file was generated by pyright.
"""

from typing import Iterator
from bip_utils.utils.typing import Literal

"""Module with helper class for data bytes."""
class DataBytes:
    """
    Data bytes class.
    It allows to get bytes in different formats.
    """
    m_data_bytes: bytes
    def __init__(self, data_bytes: bytes) -> None:
        """
        Construct class.

        Args:
            data_bytes (bytes): Data bytes
        """
        ...
    
    def Length(self) -> int:
        """
        Get length in bytes.

        Returns:
            int: Length in bytes
        """
        ...
    
    def Size(self) -> int:
        """
        Get length in bytes (same of Length()).

        Returns:
            int: Length in bytes
        """
        ...
    
    def ToBytes(self) -> bytes:
        """
        Get data bytes.

        Returns:
            bytes: Data bytes
        """
        ...
    
    def ToHex(self) -> str:
        """
        Get data bytes in hex format.

        Returns:
            str: Data bytes in hex format
        """
        ...
    
    def ToInt(self, endianness: Literal[little, big] = ...) -> int:
        """
        Get data bytes as an integer.

        Args:
            endianness ("big" or "little", optional): Endianness (default: big)

        Returns:
            int: Data bytes as an integer
        """
        ...
    
    def __len__(self) -> int:
        """
        Get length in bytes.

        Returns:
            int: Length in bytes
        """
        ...
    
    def __bytes__(self) -> bytes:
        """
        Get data bytes.

        Returns:
            bytes: Data bytes
        """
        ...
    
    def __int__(self) -> int:
        """
        Get data bytes as integer.

        Returns:
            bytes: Data bytes as integer
        """
        ...
    
    def __repr__(self) -> str:
        """
        Get data bytes representation.

        Returns:
            str: Data bytes representation
        """
        ...
    
    def __getitem__(self, idx: int) -> int:
        """
        Get the element with the specified index.

        Args:
            idx (int): Index

        Returns:
            int: Element

        Raises:
            IndexError: If the index is not valid
        """
        ...
    
    def __iter__(self) -> Iterator[int]:
        """
        Get the iterator to the current element.

        Returns:
            Iterator object: Iterator to the current element
        """
        ...
    
    def __eq__(self, other: object) -> bool:
        """
        Equality operator.

        Args:
            other (bytes, str, int or DataBytes object): Other object to compare

        Returns:
            bool: True if equal false otherwise

        Raises:
            TypeError: If the other object is not of the correct type
        """
        ...
    


