"""
This type stub file was generated by pyright.
"""

from bip_utils.bip.bip32 import Bip32KeyNetVersions
from bip_utils.bip.conf.common import BipCoinConf

"""Module for BIP86 coins configuration."""
_BIP86_BTC_KEY_NET_VER_MAIN: Bip32KeyNetVersions = ...
_BIP86_BTC_KEY_NET_VER_TEST: Bip32KeyNetVersions = ...
class Bip86Conf:
    """Class container for BIP86 configuration."""
    BitcoinMainNet: BipCoinConf = ...
    BitcoinRegTest: BipCoinConf = ...
    BitcoinTestNet: BipCoinConf = ...


