"""
This type stub file was generated by pyright.
"""

from typing import Dict
from bip_utils.bip.conf.common import BipCoinConf, BipCoins

"""Module for getting BIP84 coins configuration."""
class Bip84ConfGetterConst:
    """Class container for BIP84 configuration getter constants."""
    COIN_TO_CONF: Dict[BipCoins, BipCoinConf] = ...


class Bip84ConfGetter:
    """
    BIP84 configuration getter class.
    It allows to get the BIP84 configuration of a specific coin.
    """
    @staticmethod
    def GetConfig(coin_type: BipCoins) -> BipCoinConf:
        """
        Get coin configuration.

        Args:
            coin_type (BipCoins): Coin type

        Returns:
            BipCoinConf: Coin configuration

        Raises:
            TypeError: If coin type is not of a Bip84Coins enumerative
        """
        ...
    


