"""
This type stub file was generated by pyright.
"""

from enum import unique
from bip_utils.bip.conf.common.bip_coins import BipCoins

"""Module for BIP84 coins enum."""
@unique
class Bip84Coins(BipCoins):
    """Enumerative for supported BIP84 coins."""
    BITCOIN = ...
    LITECOIN = ...
    BITCOIN_REGTEST = ...
    BITCOIN_TESTNET = ...
    LITECOIN_TESTNET = ...


