"""
This type stub file was generated by pyright.
"""

from typing import List

"""Module for getting account addresses of SPL tokens."""
class SplTokenConst:
    """Class container for SPL token constants."""
    DEF_PROGRAM_ID: str = ...
    DEF_TOKEN_PROGRAM_ID: str = ...
    PDA_MARKER: bytes = ...
    SEED_BUMP_MAX_VAL: int = ...
    SEEDS_MAX_NUM: int = ...


class SplToken:
    """
    SPL token class.
    It provides methods for getting the account address associated to a SPL token.
    """
    @classmethod
    def GetAssociatedTokenAddress(cls, wallet_addr: str, token_mint_addr: str) -> str:
        """
        Get the account address associated to the specified SPL token.

        Args:
            wallet_addr (str)    : Wallet address
            token_mint_addr (str): Token mint address

        Returns:
            str: Associated account address

        Raises:
            ValueError: If the account address cannot be found or the specified addresses are not valid
        """
        ...
    
    @classmethod
    def GetAssociatedTokenAddressWithProgramId(cls, wallet_addr: str, token_mint_addr: str, token_program_id: str) -> str:
        """
        Get the account address associated to the specified SPL token and token program ID.

        Args:
            wallet_addr (str)     : Wallet address
            token_mint_addr (str) : Token mint address
            token_program_id (str): Token program ID

        Returns:
            str: Associated account address

        Raises:
            ValueError: If the account address cannot be found or the specified addresses or ID are not valid
        """
        ...
    
    @classmethod
    def FindPda(cls, seeds: List[bytes], program_id: str) -> str:
        """
        Find a valid PDA (Program Derived Address) and its corresponding bump seed.

        Args:
            seeds (list[bytes]): List of seeds bytes
            program_id (str)   : Program ID

        Returns:
            str: Found PDA

        Raises:
            ValueError: If the PDA cannot be found or the specified seeds or program ID are not valid
        """
        ...
    


