"""
This type stub file was generated by pyright.
"""

from typing import Optional, Union

"""Module for PBKDF2 algorithm."""
HASHLIB_USE_PBKDF2_SHA512: bool = ...
class Pbkdf2HmacSha512:
    """
    PBKDF2 HMAC-SHA512 class.
    It derives keys using PBKDF2 HMAC-SHA512 algorithm.
    """
    @staticmethod
    def DeriveKey(password: Union[bytes, str], salt: Union[bytes, str], itr_num: int, dklen: Optional[int] = ...) -> bytes:
        """
        Derive a key.

        Args:
            password (str or bytes): Password
            salt (str or bytes)    : Salt
            itr_num (int)          : Iteration number
            dklen (int, optional)  : Length of the derived key (default: SHA-512 output length)

        Returns:
            bytes: Computed result
        """
        ...
    


