"""
This type stub file was generated by pyright.
"""

from typing import Optional
from bip_utils.electrum.mnemonic_v2.electrum_v2_mnemonic import ElectrumV2MnemonicTypes
from bip_utils.utils.mnemonic import Mnemonic

"""Module for Electrum v2 mnemonic generation."""
class ElectrumV2MnemonicUtilsConst:
    """Class container for Electrum v2 mnemonic utility constants."""
    HMAC_KEY: bytes = ...


class ElectrumV2MnemonicUtils:
    """Class container for Electrum v2 mnemonic utility functions."""
    @staticmethod
    def IsValidMnemonic(mnemonic: Mnemonic, mnemonic_type: Optional[ElectrumV2MnemonicTypes] = ...) -> bool:
        """
        Get if the specified mnemonic is valid.

        Args:
            mnemonic (Mnemonic)                    : Mnemonic
            mnemonic_type (ElectrumV2MnemonicTypes): Mnemonic type

        Returns:
            bool: True if valid, false otherwise
        """
        ...
    


