"""
This type stub file was generated by pyright.
"""

from typing import Dict, Union
from bip_utils.electrum.mnemonic_v2.electrum_v2_entropy_generator import ElectrumV2EntropyBitLen
from bip_utils.electrum.mnemonic_v2.electrum_v2_mnemonic import ElectrumV2Languages, ElectrumV2MnemonicTypes, ElectrumV2WordsNum
from bip_utils.electrum.mnemonic_v2.electrum_v2_mnemonic_encoder import ElectrumV2MnemonicEncoder
from bip_utils.utils.mnemonic import Mnemonic

"""Module for Electrum v2 mnemonic generation."""
class ElectrumV2MnemonicGeneratorConst:
    """Class container for Electrum v2 mnemonic generator constants."""
    WORDS_NUM_TO_ENTROPY_LEN: Dict[ElectrumV2WordsNum, ElectrumV2EntropyBitLen] = ...
    MAX_ATTEMPTS: int = ...


class ElectrumV2MnemonicGenerator:
    """
    Electrum v2 mnemonic generator class.
    It generates 12 or 24-words mnemonic in according to Electrum wallets.
    """
    m_mnemonic_encoder: ElectrumV2MnemonicEncoder
    def __init__(self, mnemonic_type: ElectrumV2MnemonicTypes, lang: ElectrumV2Languages = ...) -> None:
        """
        Construct class.

        Args:
            mnemonic_type (ElectrumV2MnemonicTypes): Mnemonic type
            lang (ElectrumV2Languages, optional)   : Language (default: English)

        Raises:
            TypeError: If the language is not a ElectrumV2Languages enum or
                       the mnemonic type is not a ElectrumV2MnemonicTypes enum
            ValueError: If language words list is not valid
        """
        ...
    
    def FromWordsNumber(self, words_num: Union[int, ElectrumV2WordsNum]) -> Mnemonic:
        """
        Generate mnemonic with the specified words number and type from random entropy.

        Args:
            words_num (int or ElectrumV2WordsNum)  : Number of words (12)

        Returns:
            Mnemonic object: Generated mnemonic

        Raises:
            ValueError: If words number is not valid
        """
        ...
    
    def FromEntropy(self, entropy_bytes: bytes) -> Mnemonic:
        """
        Generate mnemonic from the specified entropy bytes.
        Because of the mnemonic encoding algorithm used by Electrum, the specified entropy will only be a starting
        point to find a suitable one. Therefore, it's very likely that the actual entropy bytes will be different.
        To get the actual entropy bytes, just decode the generated mnemonic.
        Please note that, to successfully generate a mnemonic, the bits of the big endian integer encoded entropy
        shall be at least 121 (for 12 words) or 253 (for 24 words). Otherwise, a mnemonic generation is not possible
        and a ValueError exception will be raised.

        Args:
            entropy_bytes (bytes): Entropy bytes

        Returns:
            Mnemonic object: Generated mnemonic

        Raises:
            ValueError: If entropy byte length is not valid or a mnemonic cannot be generated
        """
        ...
    


