"""
This type stub file was generated by pyright.
"""

from typing import Optional
from bip_utils.electrum.mnemonic_v2.electrum_v2_mnemonic import ElectrumV2Languages, ElectrumV2MnemonicTypes
from bip_utils.electrum.mnemonic_v2.electrum_v2_mnemonic_decoder import ElectrumV2MnemonicDecoder
from bip_utils.utils.mnemonic import MnemonicValidator

"""Module for Electrum v2 mnemonic validation."""
class ElectrumV2MnemonicValidator(MnemonicValidator):
    """
    Electrum v2 mnemonic validator class.
    It validates a mnemonic phrase.
    """
    m_mnemonic_decoder: ElectrumV2MnemonicDecoder
    def __init__(self, mnemonic_type: Optional[ElectrumV2MnemonicTypes] = ..., lang: Optional[ElectrumV2Languages] = ...) -> None:
        """
        Construct class.

        Args:
            mnemonic_type (ElectrumV2MnemonicTypes, optional): Mnemonic type, None for all types
            lang (ElectrumV2Languages, optional)             : Language, None for automatic detection
        """
        ...
    


