"""
This type stub file was generated by pyright.
"""

from enum import IntEnum, unique
from typing import List, Union
from bip_utils.utils.mnemonic import EntropyGenerator

"""Module for Electrum v2 mnemonic entropy generation."""
@unique
class ElectrumV2EntropyBitLen(IntEnum):
    """Enumerative for Electrum entropy bit lengths (v2)."""
    BIT_LEN_132 = ...
    BIT_LEN_264 = ...


class ElectrumV2EntropyGeneratorConst:
    """Class container for Electrum entropy generator constants (v2)."""
    ENTROPY_BIT_LEN: List[ElectrumV2EntropyBitLen] = ...


class ElectrumV2EntropyGenerator(EntropyGenerator):
    """
    Electrum entropy generator class (v2).
    It generates random entropy bytes.
    """
    def __init__(self, bit_len: Union[int, ElectrumV2EntropyBitLen]) -> None:
        """
        Construct class.

        Args:
            bit_len (int or ElectrumV2EntropyBitLen): Entropy length in bits

        Raises:
            ValueError: If the bit length is not valid
        """
        ...
    
    @staticmethod
    def IsValidEntropyBitLen(bit_len: int) -> bool:
        """
        Get if the specified entropy bit length is valid.

        Args:
            bit_len (int): Entropy length in bits

        Returns:
            bool: True if valid, false otherwise
        """
        ...
    
    @staticmethod
    def IsValidEntropyByteLen(byte_len: int) -> bool:
        """
        Get if the specified entropy byte length is valid.

        Args:
            byte_len (int): Entropy length in bytes

        Returns:
            bool: True if valid, false otherwise
        """
        ...
    
    @staticmethod
    def AreEntropyBitsEnough(entropy: Union[bytes, int]) -> bool:
        """
        Get if the entropy bits are enough to generate a valid mnemonic.

        Args:
            entropy (bytes or int): Entropy

        Returns:
            bool: True if enough, false otherwise
        """
        ...
    


