"""
This type stub file was generated by pyright.
"""

from functools import lru_cache
from bip_utils.bip.bip44_base import Bip44Base, Bip44Changes
from bip_utils.cardano.shelley.cardano_shelley_keys import CardanoShelleyPrivateKeys, CardanoShelleyPublicKeys

"""
Module for Cardano Shelley keys derivation.
Reference: https://cips.cardano.org/cips/cip11
"""
class CardanoShelley:
    """
    Cardano Shelley class.
    It allows keys derivation and addresses computation (including the staking one) in according to Cardano Shelley.
    """
    m_bip_obj: Bip44Base
    m_bip_sk_obj: Bip44Base
    @classmethod
    def FromCip1852Object(cls, bip_obj: Bip44Base) -> CardanoShelley:
        """
        Create a CardanoShelley object from the specified Cip1852 object.

        Args:
            bip_obj (Bip44Base object): Bip44Base object

        Returns:
            CardanoShelley object: CardanoShelley object

        Raises:
            ValueError: If the seed is too short
            Bip32KeyError: If the seed is not suitable for master key generation
        """
        ...
    
    def __init__(self, bip_obj: Bip44Base, bip_sk_obj: Bip44Base) -> None:
        """
        Construct class.

        Args:
            bip_obj (Bip44Base object)   : Bip44Base object
            bip_sk_obj (Bip44Base object): Bip44Base object (staking)

        Raises:
            ValueError: If the bip_sk_obj object is below account level
        """
        ...
    
    @lru_cache()
    def PublicKeys(self) -> CardanoShelleyPublicKeys:
        """
        Return the public keys.

        Returns:
            CardanoShelleyPublicKeys object: CardanoShelleyPublicKeys object
        """
        ...
    
    @lru_cache()
    def PrivateKeys(self) -> CardanoShelleyPrivateKeys:
        """
        Return the private keys.

        Returns:
            CardanoShelleyPrivateKeys object: CardanoShelleyPrivateKeys object

        Raises:
            Bip32KeyError: If the Bip32 object is public-only
        """
        ...
    
    def RewardObject(self) -> Bip44Base:
        """
        Alias for StakingObject.

        Returns:
            Bip44Base object: Bip44Base object
        """
        ...
    
    def StakingObject(self) -> Bip44Base:
        """
        Return the staking object.

        Returns:
            Bip44Base object: Bip44Base object
        """
        ...
    
    def IsPublicOnly(self) -> bool:
        """
        Get if it's public-only.

        Returns:
            bool: True if public-only, false otherwise
        """
        ...
    
    def Change(self, change_type: Bip44Changes) -> CardanoShelley:
        """
        Derive a child key from the specified change type and return a new CardanoShelley object.

        Args:
            change_type (Bip44Changes): Change type, must a Bip44Changes enum

        Returns:
            CardanoShelley object: CardanoShelley object

        Raises:
            TypeError: If change type is not a Bip44Changes enum
            Bip44DepthError: If current depth is not suitable for deriving keys
            Bip32KeyError: If the derivation results in an invalid key
        """
        ...
    
    def AddressIndex(self, addr_idx: int) -> CardanoShelley:
        """
        Derive a child key from the specified address index and return a new CardanoShelley object.

        Args:
            addr_idx (int): Address index

        Returns:
            CardanoShelley object: CardanoShelley object

        Raises:
            Cip1852DepthError: If current depth is not suitable for deriving keys
            Bip32KeyError: If the derivation results in an invalid key
        """
        ...
    


