"""
This type stub file was generated by pyright.
"""

from functools import lru_cache
from bip_utils.bip.bip32 import Bip32PrivateKey, Bip32PublicKey
from bip_utils.bip.conf.common import BipCoinConf

"""Module for Cardano Shelley keys handling."""
class CardanoShelleyPublicKeys:
    """
    Cardano Shelley public key class.
    It contains 2 CIP-1852 public keys (address + staking) and allows to get the Cardano Shelley address from them.
    """
    m_pub_addr_key: Bip32PublicKey
    m_pub_sk_key: Bip32PublicKey
    m_coin_conf: BipCoinConf
    def __init__(self, pub_addr_key: Bip32PublicKey, pub_sk_key: Bip32PublicKey, coin_conf: BipCoinConf) -> None:
        """
        Construct class.

        Args:
            pub_addr_key (Bip32PublicKey object): Bip32PublicKey object (address)
            pub_sk_key (Bip32PublicKey object)  : Bip32PublicKey object (staking)
            coin_conf (BipCoinConf object)      : BipCoinConf object
        """
        ...
    
    def AddressKey(self) -> Bip32PublicKey:
        """
        Get the address public key.

        Returns:
            Bip32PublicKey object: Bip32PublicKey object
        """
        ...
    
    def RewardKey(self) -> Bip32PublicKey:
        """
        Alias for StakingKey.

        Returns:
            Bip32PublicKey object: Bip32PublicKey object
        """
        ...
    
    def StakingKey(self) -> Bip32PublicKey:
        """
        Get the staking address public key.

        Returns:
            Bip32PublicKey object: Bip32PublicKey object
        """
        ...
    
    def ToRewardAddress(self) -> str:
        """
        Alias for ToStakingAddress.

        Returns:
            str: Reward address string

        Raises:
            ValueError: If the public key is not correspondent to an address index level
        """
        ...
    
    @lru_cache()
    def ToStakingAddress(self) -> str:
        """
        Return the staking address correspondent to the public key.

        Returns:
            str: Staking address string

        Raises:
            ValueError: If the public key is not correspondent to an address index level
        """
        ...
    
    @lru_cache()
    def ToAddress(self) -> str:
        """
        Return the address correspondent to the public key.

        Returns:
            str: Address string

        Raises:
            ValueError: If the public key is not correspondent to an address index level
        """
        ...
    


class CardanoShelleyPrivateKeys:
    """
    Cardano Shelley private key class.
    It contains 2 BIP32 private keys (address + staking).
    """
    m_priv_addr_key: Bip32PrivateKey
    m_priv_sk_key: Bip32PrivateKey
    m_coin_conf: BipCoinConf
    def __init__(self, priv_addr_key: Bip32PrivateKey, priv_sk_key: Bip32PrivateKey, coin_conf: BipCoinConf) -> None:
        """
        Construct class.

        Args:
            priv_addr_key (Bip32PrivateKey object): Bip32PrivateKey object (address)
            priv_sk_key (Bip32PrivateKey object)  : Bip32PrivateKey object (staking)
            coin_conf (BipCoinConf object)        : BipCoinConf object
        """
        ...
    
    def AddressKey(self) -> Bip32PrivateKey:
        """
        Get the address private key.

        Returns:
            Bip32PrivateKey object: Bip32PrivateKey object
        """
        ...
    
    def RewardKey(self) -> Bip32PrivateKey:
        """
        Alias for StakingKey.

        Returns:
            Bip32PrivateKey object: Bip32PrivateKey object
        """
        ...
    
    def StakingKey(self) -> Bip32PrivateKey:
        """
        Get the staking address private key.

        Returns:
            Bip32PrivateKey object: Bip32PrivateKey object
        """
        ...
    
    @lru_cache()
    def PublicKeys(self) -> CardanoShelleyPublicKeys:
        """
        Get the public keys correspondent to the private ones.

        Returns:
            CardanoShelleyPublicKeys object: CardanoShelleyPublicKeys object
        """
        ...
    


