"""
This type stub file was generated by pyright.
"""

from enum import Enum, unique
from typing import Dict

"""Module for base58 decoding/encoding."""
@unique
class Base58Alphabets(Enum):
    """Enumerative for Base58 alphabet."""
    BITCOIN = ...
    RIPPLE = ...


class Base58Const:
    """Class container for Base58 constants."""
    RADIX: int = ...
    CHECKSUM_BYTE_LEN: int = ...
    ALPHABETS: Dict[Base58Alphabets, str] = ...


class Base58Utils:
    """Class container for Base58 utility functions."""
    @staticmethod
    def ComputeChecksum(data_bytes: bytes) -> bytes:
        """
        Compute Base58 checksum.

        Args:
            data_bytes (bytes): Data bytes

        Returns:
            bytes: Computed checksum
        """
        ...
    


class Base58Encoder:
    """Base58 encoder class. It provides methods for encoding and checksum encoding to Base58 format."""
    @staticmethod
    def Encode(data_bytes: bytes, alph_idx: Base58Alphabets = ...) -> str:
        """
        Encode bytes into a Base58 string.

        Args:
            data_bytes (bytes)                  : Data bytes
            alph_idx (Base58Alphabets, optional): Alphabet index, Bitcoin by default

        Returns:
            str: Encoded string

        Raises:
            TypeError: If alphabet index is not a Base58Alphabets enumerative
        """
        ...
    
    @staticmethod
    def CheckEncode(data_bytes: bytes, alph_idx: Base58Alphabets = ...) -> str:
        """
        Encode bytes into Base58 string with checksum.

        Args:
            data_bytes (bytes)                  : Data bytes
            alph_idx (Base58Alphabets, optional): Alphabet index, Bitcoin by default

        Returns:
            str: Encoded string with checksum

        Raises:
            TypeError: If alphabet index is not a Base58Alphabets enumerative
        """
        ...
    


class Base58Decoder:
    """Base58 decoder class. It provides methods for decoding and checksum decoding Base58 format."""
    @staticmethod
    def Decode(data_str: str, alph_idx: Base58Alphabets = ...) -> bytes:
        """
        Decode bytes from a Base58 string.

        Args:
            data_str (str)                      : Data string
            alph_idx (Base58Alphabets, optional): Alphabet index, Bitcoin by default

        Returns:
            bytes: Decoded bytes

        Raises:
            TypeError: If alphabet index is not a Base58Alphabets enumerative
        """
        ...
    
    @staticmethod
    def CheckDecode(data_str: str, alph_idx: Base58Alphabets = ...) -> bytes:
        """
        Decode bytes from a Base58 string with checksum.

        Args:
            data_str (str)                      : Data string
            alph_idx (Base58Alphabets, optional): Alphabet index, Bitcoin by default

        Returns:
            bytes: Decoded bytes (checksum removed)

        Raises:
            ValueError: If the string is not a valid Base58 format
            TypeError: If alphabet index is not a Base58Alphabets enumerative
            Base58ChecksumError: If checksum is not valid
        """
        ...
    


