# Generated by Django 5.2.8 on 2025-11-15 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVEModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('year', models.IntegerField()),
                ('cve_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('version', models.CharField()),
                ('std_binary_path', models.FilePathField()),
                ('std_tcp_port', models.IntegerField()),
                ('used_tcp_port', models.IntegerField()),
                ('non_categorized_metadata', models.JSONField()),
                ('known_vulnerabilities', models.ManyToManyField(to='base.cvemodel')),
            ],
        ),
        migrations.CreateModel(
            name='HostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('operative_system_stats', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='host_os_set', to='base.softwaremodel')),
                ('software_stats', models.ManyToManyField(related_name='host_software_set', to='base.softwaremodel')),
            ],
        ),
    ]
