# Generated by Django 5.2.8 on 2025-11-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvemodel',
            name='summary',
            field=models.CharField(default=None),
        ),
    ]
