"""
This type stub file was generated by pyright.
"""

from types import ModuleType
from typing import Any
from .server import Server

logger = ...
DEFAULT_HOST = ...
DEFAULT_PORT = ...
class CommandLineInterface:
    """
    Acts as the main CLI entry point for running the server.
    """
    description = ...
    server_class = Server
    def __init__(self) -> None:
        ...
    
    @classmethod
    def entrypoint(cls) -> None: # -> None:
        """
        Main entrypoint for external starts.
        """
        ...
    
    def load_asgi_app(self, asgi_app_path: str) -> ModuleType|Any: # -> ModuleType | Any:
        """
        Return the imported application.
        """
        ...
    
    def run(self, args: list[str]) -> None: # -> None:
        """
        Pass in raw argument list and it will decode them
        and run the server.
        """
        ...
    


