"""
This type stub file was generated by pyright.
"""

HEADER_NAME_RE = ...
def import_by_path(path): # -> ModuleType | Any:
    """
    Given a dotted/colon path, like project.module:ClassName.callable,
    returns the object at the end of the path.
    """
    ...

def header_value(headers, header_name):
    ...

def parse_x_forwarded_for(headers, address_header_name=..., port_header_name=..., proto_header_name=..., original_addr=..., original_scheme=...): # -> tuple[Any | None, Any | None] | tuple[list[Any] | Any | None, str | Any | None]:
    """
    Parses an X-Forwarded-For header and returns a host/port pair as a list.

    @param headers: The twisted-style object containing a request's headers
    @param address_header_name: The name of the expected host header
    @param port_header_name: The name of the expected port header
    @param proto_header_name: The name of the expected proto header
    @param original_addr: A host/port pair that should be returned if the headers are not in the request
    @param original_scheme: A scheme that should be returned if the headers are not in the request
    @return: A list containing a host (string) as the first entry and a port (int) as the second.
    """
    ...

