"""
This type stub file was generated by pyright.
"""

from typing import Tuple
from bip_utils.bech32.bech32_base import Bech32DecoderBase, Bech32EncoderBase

"""
Module for segwit bech32/bech32m decoding/encoding.

References:
    https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki
    https://github.com/bitcoin/bips/blob/master/bip-0350.mediawiki
"""
class SegwitBech32Const:
    """Class container for Segwit Bech32 constants."""
    SEPARATOR: str = ...
    CHECKSUM_STR_LEN: int = ...
    WITNESS_PROG_MIN_BYTE_LEN: int = ...
    WITNESS_PROG_MAX_BYTE_LEN: int = ...
    WITNESS_VER_BECH32: int = ...
    WITNESS_VER_MAX_VAL: int = ...
    WITNESS_VER_ZERO_DATA_BYTE_LEN: Tuple[int, int] = ...


class SegwitBech32Encoder(Bech32EncoderBase):
    """
    Segwit Bech32 encoder class.
    It provides methods for encoding to Segwit Bech32 format.
    """
    @classmethod
    def Encode(cls, hrp: str, wit_ver: int, wit_prog: bytes) -> str:
        """
        Encode to Segwit Bech32.

        Args:
            hrp (str)       : HRP
            wit_ver (int)   : Witness version
            wit_prog (bytes): Witness program

        Returns:
            str: Encoded address

        Raises:
            ValueError: If the data is not valid
        """
        ...
    


class SegwitBech32Decoder(Bech32DecoderBase):
    """
    Segwit Bech32 decoder class.
    It provides methods for decoding Segwit Bech32 format.
    """
    @classmethod
    def Decode(cls, hrp: str, addr: str) -> Tuple[int, bytes]:
        """
        Decode from Segwit Bech32.

        Args:
            hrp (str) : Human readable part
            addr (str): Address

        Returns:
            tuple[int, bytes]: Witness version (index 0) and witness program (index 1)

        Raises:
            Bech32ChecksumError: If the checksum is not valid
            ValueError: If the bech32 string is not valid
        """
        ...
    


