"""
This type stub file was generated by pyright.
"""

from typing import Optional, Union
from bip_utils.bip.bip39 import Bip39Languages, IBip39SeedGenerator
from bip_utils.utils.mnemonic import Mnemonic

"""Module for Substrate mnemonic seed generation."""
class SubstrateBip39SeedGenerator(IBip39SeedGenerator):
    """
    Substrate BIP39 seed generator class. It implements a variant for generating seed introduced by Polkadot.
    Reference: https://github.com/paritytech/substrate-bip39
    """
    m_entropy_bytes: bytes
    def __init__(self, mnemonic: Union[str, Mnemonic], lang: Optional[Bip39Languages] = ...) -> None:
        """
        Construct class.

        Args:
            mnemonic (str or Mnemonic object): Mnemonic
            lang (Bip39Languages, optional)  : Language, None for automatic detection

        Raises:
            ValueError: If the mnemonic is not valid
        """
        ...
    
    def Generate(self, passphrase: str = ...) -> bytes:
        """
        Generate the seed using the specified passphrase.

        Args:
            passphrase (str, optional): Passphrase, empty if not specified

        Returns:
            bytes: Generated seed
        """
        ...
    


